### ISSUE TITLE
Scraping array of items

### ISSUE THREAD

**Issue by JakeAustwick** [scrapinghub/portia#1]
I see no mailing list, so sorry about creating an GitHub issue regarding this. I can see this project becoming popular, so a mailing list is probably favourable. 

Anyway, to my actual question. Is there a way to scrape multiple items and store them in an array, let's say I'm scraping a category on a eccomerce site, do I have to go down and click on every single image, every title etc and assign them to a field such asproduct1_image_url, product1_title .Is there a way I can just select all the images and create an array of them?

Right now if I assign all of them to the same field (http://imgur.com/PjAhMbA) then I just get all the text joined together when extracted (http://imgur.com/bgam0AK).

Maybe I'm missing something, or this is this the intended functionality?

**Comment by ruairif** [comment]
Available in Portia 2.0
