### ISSUE TITLE
[non-urgent] SEO tip - include term "WYSIWYG" in the description

### ISSUE THREAD

**Issue by hangtwenty** [scrapinghub/portia#111]
This looks like an excellent tool (and soon, excellent service). In fact it's just what I was looking for. It took me a few hops to find it, and I just wanted to point out that my first search term was **"WYSIWYG web scraper."** Maybe that should be mentioned in the README? Just a thought!

**Comment by vedantrathore** [comment]
@hangtwenty is it still relevant? If so should I do it?

**Comment by hangtwenty** [comment]
@vedantrathore Like the PR I just made. I did my commit through the GitHub web interface and weirdly, it happened 3 times. Sorry about that...

**Comment by hangtwenty** [comment]
OK, fixed that issue (closed other PR, opened new one that is cleaned up)
