### ISSUE TITLE
Question: is there any way to add custom selector in portia

### ISSUE THREAD

**Issue by geetanshjindal** [scrapinghub/portia#115]
Example : I want to add following code to portia, this code works fine in scrapy

meta = hxs.xpath('//meta[@name=\'description\']/@content').extract()

is there any possible way to add selectors manually to portia

**Comment by ruairif** [comment]
Available in Portia 2.0
Create a new annotation by pressing the dropdown arrow beside the item and select add new annotation.
Click on the settings wheel for the new annotation
Add a new CSS or XPath selector
