### ISSUE TITLE
"Test spider" improvement 

### ISSUE THREAD

**Issue by oltarasenko** [scrapinghub/portia#117]
Currently it's quite difficult to test spiders created by portia. For example after annotating several pages it;s almost impossible to understand how successful the extraction passed in general.
Even more, deploying new changes take 3 clicks from given spider. So in general, I would want to see requests and extracted items in portia UI... So it's possible to review extraction on the go. 

But for now, can we duplicate the publish/deploy functionality on spider page maybe like this http://dl.dropbox.com/u/15708031/Selection_259.png

**Comment by ruairif** [comment]
Publish and deploy are now both done when you click `publish`. You still need to go to the project page though. Is this OK?
