### ISSUE TITLE
Renaming an item deselects it from the 'Extracted item type' drop-down in template

### ISSUE THREAD

**Issue by rdowinton** [scrapinghub/portia#120]
When editing a template in Portia, you can go to Extracted item -> Edit items to edit items. If you rename the item that is currently selected in the Extracted item type drop-down, it will become deselected. If you click 'Continue browsing' it will fail to save the template; when you go back into the template the Extracted item type value will have reverted to default. It will also disassociate any annotations from fields that don't exist in the default item.

**Comment by Youwotma** [comment]
Now items get assigned an id that won't change during it's lifetime, so renaming an item won't cause problems anymore.
