### ISSUE TITLE
Portia spider conflicts with manual scrapy spider

### ISSUE THREAD

**Issue by federicozaiter** [scrapinghub/portia#125]
I haven't been able to fully replicate the error but I think there's enough to make progress to fix it.
I tried portia on a project where I already had other spiders and it conflicted with them. When I tried to run the portia spider it would first start and try to run the manual spider I had on the project instead and immediatelly stop with outcome: no_reason. In the logs I could see this: Unhandled error in Deferred. Please see [here](https://staging.scrapinghub.com/p/5989/job/6/2/#log/line/8) . You can also try to run that portia spider named "www.ovaciondigital.com.uy" and see how it fails.

I tried to replicate it in [this other project](https://staging.scrapinghub.com/p/7200/) but even though I couldn't make it fail, you can see [in the logs](https://staging.scrapinghub.com/p/7200/job/1/2/#log/line/3) that it calls the manual spider but it somehow still works.

**Comment by ruairif** [comment]
@federicozaiter Have you managed to reproduce this recently?
Portia should no longer allow name collisions with existing spiders on dash.

**Comment by federicozaiter** [comment]
Hi @ruairif, I haven't. I'll close this one.
