### ISSUE TITLE
ImportError: No module named jsonschema.exceptions

### ISSUE THREAD

**Issue by Euphorbium** [scrapinghub/portia#13]
After correct installation, when I try to run 

> twistd -n slyd

I get 

> Traceback (most recent call last):
>   File "/usr/local/bin/twistd", line 14, in <module>
>     run()
>   File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 27, in run
>     app.run(runApp, ServerOptions)
>   File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 642, in run
>     runApp(config)
>   File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 23, in runApp
>     _SomeApplicationRunner(config).run()
>   File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 376, in run
>     self.application = self.createOrGetApplication()
>   File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 436, in createOrGetApplication
>     ser = plg.makeService(self.config.subOptions)
>   File "/home/euphorbium/Projects/mtg/scraper/portia-master/slyd/slyd/tap.py", line 55, in makeService
>     root = create_root(config)
>   File "/home/euphorbium/Projects/mtg/scraper/portia-master/slyd/slyd/tap.py", line 27, in create_root
>     from slyd.crawlerspec import (CrawlerSpecManager,
>   File "/home/euphorbium/Projects/mtg/scraper/portia-master/slyd/slyd/crawlerspec.py", line 12, in <module>
>     from jsonschema.exceptions import ValidationError
> ImportError: No module named jsonschema.exceptions

**Comment by abersh** [comment]
how to fix this error "importerror no module named simplejson" i'm using django 1.6.11
