### ISSUE TITLE
Making the use of variants and navigating the HTML hierarchy easier when annotating a template

### ISSUE THREAD

**Issue by federicozaiter** [scrapinghub/portia#133]
When using variants or navigating the HTML hierarchy to scrape specific content it's quite harder on portia templates than when using autoscraping. While making annotations on a template in autoscraping you are able to edit everything from the annotation altogether as you can see here: 
![image](https://cloud.githubusercontent.com/assets/9220740/5570656/6553d9ae-8f6c-11e4-931b-a53f64009d51.png)
However, when on portia you have two places to edit the annotations, you can do it directly or on the side panel where you can also edit advanced settings. 
![image](https://cloud.githubusercontent.com/assets/9220740/5570662/89967db2-8f6c-11e4-9094-d88a27bf68fd.png) 
![image](https://cloud.githubusercontent.com/assets/9220740/5570670/a49a3388-8f6c-11e4-88b1-465a13d3a51d.png)

I believe it would be much easier if it was similar to autoscraping in that sense. I think all of this could be added to the box (the one on the second picture) when you just click on an element while keeping the current editing way available at the side panel. Maybe, there could be an "advanced" button on that box that would just extend it to look like the one in autoscraping. I mean this to keep it as simple as it is now, at first, and then enable advanced editing if the user needs it.

**Comment by aleafboat** [comment]
can you give me a demo of Portia  that how to config

**Comment by ruairif** [comment]
@federicozaiter @almeidaf I've been working towards changing how this works lately. So far this is what my proposed changes to it look like.
![start_annotation](https://cloud.githubusercontent.com/assets/6472969/6330693/691be7de-bb72-11e4-96cc-bb880155f23c.png)
`Adding new annotation`
![field added](https://cloud.githubusercontent.com/assets/6472969/6330694/691e9c54-bb72-11e4-9390-d2b3fc6c9579.png)
`Selecting an attribute to extract`
![add_new_field](https://cloud.githubusercontent.com/assets/6472969/6330692/691b913a-bb72-11e4-8720-9f6179573492.png)
`Creating a new field` 
![advanced_view](https://cloud.githubusercontent.com/assets/6472969/6330696/6926e0a8-bb72-11e4-9fc1-f1214ff54493.png)
`New advanced view`
![with_ignores](https://cloud.githubusercontent.com/assets/6472969/6330695/691f375e-bb72-11e4-97a8-526504b09fb7.png)
`Added an ignored sub element`
![in_box](https://cloud.githubusercontent.com/assets/6472969/6330803/585e316c-bb73-11e4-9948-29ce76b8ccab.png)
`Edit annotation in toolbox too`

With these changes the "Annotation Options" section of the toolbox is gone and all changes can be carried out using the floating box or it's corresponding instance in the template toolbox. Obviously the element selection feature is still missing as I haven't gotten around to implementing it yet. What I have in mind for the element selection is to use something like [jBreadcrumbs](http://www.comparenetworks.com/developers/jqueryplugins/jbreadcrumb.html) and splitting this into parent and child elements to that it's not as long.

Please give me your thoughts, ideas and feedback!

**Comment by federicozaiter** [comment]
Great! I wonder if it could extend the box when on the advanced view instead of just showing the variant as if on another page. I mean this for when you eventually add the HTML hierarchy navigation so that the user can check on the different attributes in each level without going back and forward between the normal and the advanced view. In this case the advanced view button could be some sort of toggle button.
As for the jBreadcrumbs it looks totally fine!

**Comment by ruairif** [comment]
What about having the attributes show up in a tooltip when a user hovers over the element? I was trying to keep the size of the box down with this design. It's probably 25% larger than it was before already.

**Comment by federicozaiter** [comment]
I see. I meant that for when navigating the HTML hierarchy, so if by element you refer to the elements of the breadcrumb so that when hovering over them one can see the attributes of each, that would be great.

**Comment by ruairif** [comment]
Yup that's what I mean.
Have you any other ideas or suggestions?

**Comment by federicozaiter** [comment]
Nope, not at the moment. What you suggested would solve this issue already.
Looking forward to trying this feature out.

**Comment by ruairif** [comment]
This is not available from dash staging. Have you got any improvement ideas?
