### ISSUE TITLE
Start urls edit all

### ISSUE THREAD

**Issue by almeidaf** [scrapinghub/portia#136]
maybe its just me but i dont like the current way of editing start urls i prefere the big box of AS, i think it would be a good idea to add a "Edit All" button to open up all start urls on a text box.

**Comment by ruairif** [comment]
This is available from dash staging.
Please give me your thoughts/comments on it.

**Comment by redapple** [comment]
@ruairif , @almeidaf probably doesn't have access to our staging dash :)

**Comment by ruairif** [comment]
![basic](https://cloud.githubusercontent.com/assets/6472969/6481792/5bb9f706-c258-11e4-99ed-4bfd3076f362.png)
![editing](https://cloud.githubusercontent.com/assets/6472969/6481794/5cecd800-c258-11e4-91bb-05a9128dea82.png)
Here are pictures of it in action then :)

**Comment by redapple** [comment]
Cosmetic comment: could the URLs be left-aligned, and also in fixed-width font?

**Comment by almeidaf** [comment]
that looks good , and even better if you make the suggested cosmetic changes ;)

**Comment by ruairif** [comment]
![monspaced](https://cloud.githubusercontent.com/assets/6472969/6482729/0ee972b8-c261-11e4-81c8-ae235e382ace.png)
What about adding new line characters between the urls?
