### ISSUE TITLE
Question: how to store data in json

### ISSUE THREAD

**Issue by SophiaCY** [scrapinghub/portia#137]
Hi, recently I have installed portia and it's quite good. But since I'm not very familiar with it, I have met a problem:
In my template I used variants to scrape the website and it worked well when I clicked continue browsing or turned to a similiar page.  However, when I started running the portia spider in cmd, it could successfully  scrape data yet failed to store the whole data scraped in the json file. I found that in the json file only the data in the page I annotated were stored.
I guess the problem is "WARNING: Dropped: Duplicate product scraped at <http://bbs.chinadaily.com.cn/forum-83-206.html>, first one was scraped at <http://bbs.chinadaily.com.cn/forum-83-2.html>" (it appeared in cmd when the spider was running), but I don't know how to solve the problem.
I hope someone can help me as soon as possible.
Thanks very much!

**Comment by ruairif** [comment]
For portiacrawl if you add `-o FILENAME.json` items will be saved to the file you specify.
Running `portiacrawl -h` gives more info.

**Comment by SophiaCY** [comment]
Sorry, maybe I didn't express my problem clearly. 
I want to scrape data in chinadaily's forum, so I annotate the page http://bbs.chinadaily.com.cn/forum-83-2.html and in crawling, I set the follow pattern as http://bbs.chinadaily.com.cn/forum-83-\d+.html

![_2015-02-11t03-33-52 335z](https://cloud.githubusercontent.com/assets/10937666/6141531/3bc004b2-b1e2-11e4-96d8-b0157af11c1e.png)

In my template I use variants to scrape items: 

![_2015-02-10t09-15-44 802z](https://cloud.githubusercontent.com/assets/10937666/6141556/b42cc782-b1e2-11e4-989c-26e1d1b8928f.png)

and it works well when I click continue browsing or turn to a similiar page: 

![_2015-02-11t03-40-59 033z](https://cloud.githubusercontent.com/assets/10937666/6141584/0b0e4b0c-b1e3-11e4-825b-c9ca8734eb60.png)

So I start to run the spider in console:
cd C:\Users\Administrator\portia\portia\slybot\slybot
portiacrawl C:\Users\Administrator\portia\portia\slyd\data\projects\new_project bbs.chinadaily.com.cn -o itemsss.json -t json

Then I can see the data I want in my console, but when the spider finished, only the items in http://bbs.chinadaily.com.cn/forum-83-2.html are stored:
![qq 20150211114930](https://cloud.githubusercontent.com/assets/10937666/6141728/8d5eed5e-b1e4-11e4-9c01-97aaa4695afd.jpg)

![1](https://cloud.githubusercontent.com/assets/10937666/6141801/ac156254-b1e5-11e4-9ffc-09e1055f9de4.png)



I don't know what I'm missing...

Thanks very much!!!;)

**Comment by ruairif** [comment]
What are your start urls?

**Comment by SophiaCY** [comment]
http://bbs.chinadaily.com.cn/forum-83-2.html
and it's also the page I annotate.

![_2015-02-11t10-04-58 972z](https://cloud.githubusercontent.com/assets/10937666/6145046/a174fb2e-b218-11e4-81bd-69c156e2b2de.png)

**Comment by ruairif** [comment]
Which links are green when you check the 'Overlay blocked links' box?

**Comment by SophiaCY** [comment]
Just the links shown in the picture:
![_2015-02-11t11-29-21 215z](https://cloud.githubusercontent.com/assets/10937666/6146126/5348fee4-b224-11e4-82dc-89a8f0ce1c29.png)

**Comment by ruairif** [comment]
Does it work if you create a file `slybot/local_slybot_settings.py` with the following content?:

    ITEM_PIPELINES = {'slybot.dupefilter.DupeFilterPipeline': None}

**Comment by SophiaCY** [comment]
Yes it works when I store data in a json file. Thank you very much!!!;)
However, because the data in the json file can't be imported to the database directly, I have to store data in a csv file. But when I run the spider with: 
portiacrawl C:\Users\Administrator\portia\portia\slyd\data\projects\new_project bbs.chinadaily.com.cn -t csv -o p.csv
the spider runs successfully but only the names of the items are stored in the csv file.

![2](https://cloud.githubusercontent.com/assets/10937666/6161104/f5b040b6-b2a6-11e4-9674-3473ddf2d311.png)

![3](https://cloud.githubusercontent.com/assets/10937666/6161107/fb346ab2-b2a6-11e4-9de7-2c1f6833820a.png)

Thanks a lot!

**Comment by ruairif** [comment]
I'm not sure what's happening with your CSV file but with your JSON file there are a few other things you could try that might make it more suitable to being inserted into the database.

The duplicate filter was being triggered because all of your fields are marked as variant and as such only the first item is being kept. You could solve this by adding a dummy non variant field that is different on each page.
Another option you could try would be to use the Split Variants Middleware to create individual items for each entry. I'm not sure if these instructions are exactly correct but it would be great if you could try it out:

    pip install scrapylib

Then in your `local_slybot_settings.py` file add:

    SPIDER_MIDDLEWARES = {'slybot.spiderlets.SpiderletsMiddleware': 998,
                          'scrapylib.splitvariants.SplitVariantsMiddleware': 999}
    SPLITVARIANTS_ENABLED = True

Please report back if it goes well or if you need more help.

**Comment by SophiaCY** [comment]
Thanks a lot!
I have tried your second method and it successfully created individual items for each entry.
Here is the result:
the former:
![5](https://cloud.githubusercontent.com/assets/10937666/6168690/623eb66c-b302-11e4-9070-ddbeba1df48c.png)
![6](https://cloud.githubusercontent.com/assets/10937666/6168872/1a8396c4-b304-11e4-8b01-3e66e765827c.png)

the latter:
![7](https://cloud.githubusercontent.com/assets/10937666/6168884/2cf14d9c-b304-11e4-9f1c-37b9b1e07db9.png)
![8](https://cloud.githubusercontent.com/assets/10937666/6168894/358710ea-b304-11e4-9332-2910a4e682f6.png)

By the way, then I tried to store data in the csv file and they're successfully stored! Maybe it's your second method that helped me solve the problem.
It's very nice of you! Thank you very much!

**Comment by ruairif** [comment]
You're very welcome.
Thank you for testing it I'll add that info to the README next time I update it.

**Comment by SophiaCY** [comment]
My pleasure ^_^

**Comment by maoouyang** [comment]
how to store in mysql ? I am puzzle！！

**Comment by maoouyang** [comment]
I am first use of portia,I had store data to json,but I dont kown how to store in mysql ..thanks.

**Comment by blacking** [comment]
same problem? hello maoouyang have you understand how to do?

**Comment by AlexTan-b-z** [comment]
I set same with you,but I alwals received :
2016-08-25 16:03:37 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
why?
and the json file is empty,only have [.
who can help me?  thank you!

**Comment by AlexTan-b-z** [comment]
Now,my question is same with you.
Json only the first page are stored.
CSV only the names of the items.
However I use the both two methods,it doesn't work.
How can I do it?
