### ISSUE TITLE
Unexpected error response 

### ISSUE THREAD

**Issue by sornalingam** [scrapinghub/portia#139]
When i try to scrap some pages i am getting the below error 

unexpected error response: [Failure instance: Traceback: : Unsupported URL scheme 'about': no handler available for that scheme C:\Python27\lib\site-packages\scrapy\core\downloader\middleware.py:38:process_request C:\Python27\lib\site-packages\scrapy\core\downloader\__init__.py:123:_enqueue_request C:\Python27\lib\site-packages\scrapy\core\downloader\__init__.py:143:_process_queue C:\Python27\lib\site-packages\scrapy\core\downloader\__init__.py:154:_download --- --- C:\Python27\lib\site-packages\scrapy\utils\defer.py:39:mustbe_deferred C:\Python27\lib\site-packages\scrapy\core\downloader\handlers\__init__.py:39:download_request ]

in the portia UI

**Comment by ruairif** [comment]
You tried to download a badly formatted URL. Something with 'about' at the start.
What was the URL you were trying to scrape?

**Comment by sornalingam** [comment]
https://eapplicant.northshore.org/psc/psapp/EMPLOYEE/HRMS/c/HRS_HRAM.HRS_CE.GBL?&

I have tried this URL

**Comment by ruairif** [comment]
Does this error occur when you press test spiders?

**Comment by sornalingam** [comment]
I have pasted this below URL in the page 

https://eapplicant.northshore.org/psc/psapp/EMPLOYEE/HRMS/c/HRS_HRAM.HRS_CE.GBL?&

And clicked "New spider". After that i have selected the very first URL to Annotation the page but got the above error

**Comment by ruairif** [comment]
I can't recreate your issue. I just end up on a page saying that I need cookies enabled.
Do you have the login fields filled out?

**Comment by sornalingam** [comment]
Hi @ruairif 
 
I have tried the below URL 

https://eapplicant.northshore.org/psc/psapp/EMPLOYEE/HRMS/c/HRS_HRAM.HRS_CE.GBL?&

first time it  would say need cookies enabled. but when you try  second time it will work  and display the home page. 

If we click any URL in the Home page then we will get the above error.

**Comment by ruairif** [comment]
The href is being changed from `javascript:submitAction_win0(document.win0,'POSTINGTITLE$0');` to `about:blank`. This is due to there being no JS support on the backend for Portia there are plans to add JS support but I don't have an exact timeframe for when this will be implemented.
Discussions for JS support will be discussed at #2
