### ISSUE TITLE
No such file or directory 

### ISSUE THREAD

**Issue by sornalingam** [scrapinghub/portia#141]
I have downloaded new version of portia (portia beta). I have created a spider and scheduled using Scrapyd. But while scheduling i got the below error response 

Packing version 1424251717
Deploying to project "vm" in http://localhost:6800/addversion.json
Server response (200):
{"status": "error", "message": "IOError: [Errno 2] No such file or directory: u'
c:\\\\users\\\\sornal~1\\\\appdata\\\\local\\\\temp\\\\slybot-n_m7gw\\\\spiders\
\\\stackoverflow\\\\e036-5101-521d.json'"}

I am using Windows. I have copied the project from portia/data/project   to  deploy/project

Thanks,

**Comment by ruairif** [comment]
Could you post the git commit id of the version of Portia that you are using and the folder structure of your project?

**Comment by sornalingam** [comment]
Sure : 8210941dba1c0eb7ea30e12eefdfbc81b0646b21. 

In the portia folder :  

Project :  E:\usr\portia-master\slyd\data\projects\new_project_2
                           \spiders
                                        \ github.com
                                                            \ a9f1-0e81-b02f.json   ---Template
                                         \__init__
                                          \github.com.json
                                          \settings.py
                              \extractor.json
                              \items.json
                              \project.json
                              \scrapy.cfg
                              \setup.py 

Deploy : E:\usr\deploy\new_project_2 
and the structure is same as the above. I have added the scrapyd details in the scrapy.cfg file 

and run like below 

D:\usr\deploy\new_project_2>python C:\Python27\Scripts\scrapyd-deploy scrapyd -p git

**Comment by ruairif** [comment]
Is this the folder structure?

    ├── __init__.py
    ├── extractor.json
    ├── items.json
    ├── project.json
    ├── scrapy.cfg
    ├── settings.py
    ├── setup.py
    └── spiders
        ├── github.com.json
        └── github.com
            └── a9f1-0e81-b02f.json

What does the stackoverflow.json spider look like? Does it have templates stored within the json file or externally in separate template files?

**Comment by ruairif** [comment]
Closing for now. Will reopen if more help is needed

**Comment by mezuqu** [comment]
same here.

$ scrapyd-deploy local -p default
Packing version 1426136458
Deploying to project "default" in http://localhost:6800/addversion.json
Server response (200):
{"status": "error", "message": "IOError: [Errno 2] No such file or directory: u'/tmp/slybot-x_d4_M/spiders/www.mywebsite.com/products.json'"}

How can I redirect scrapyd to the right folder?

**Comment by JFENS** [comment]
> same here.
> 
> $ scrapyd-deploy local -p default
> Packing version 1426136458
> Deploying to project "default" in http://localhost:6800/addversion.json
> Server response (200):
> {"status": "error", "message": "IOError: [Errno 2] No such file or directory: u'/tmp/slybot-x_d4_M/spiders/www.mywebsite.com/products.json'"}
> 
> How can I redirect scrapyd to the right folder?

Have you had any luck with this? I am getting a similar error
