### ISSUE TITLE
Requirements.txt missing packages

### ISSUE THREAD

**Issue by richardpenman** [scrapinghub/portia#142]
I needed to additionally install the following python packages to run Portia:
pip install six w3lib cssselect numpy queuelib pyOpenSSL==0.13

Along with these header files (on Debian):
libxml2-dev libxslt1-dev libffi-dev

**Comment by ruairif** [comment]
Those are all dependencies of Scrapy and should have been installed through `pip install -r requirements.txt`.

The requirements needed for debian can be seen within the provision.sh file used by Vagrant. Those headers are needed for lxml. Information on installing lxml can be found around the web.

**Comment by richardpenman** [comment]
Strange they needed to be installed manually.

Is there a plan to make Portia itself installable via pip, or not practical?

**Comment by ruairif** [comment]
I haven't looked into it yet but It should be possible. It would involve packaging all of the compiled assets that are usually installed through npm and compiled by gulp with the python package.
