### ISSUE TITLE
Save error when clicking 'Annotate this page'

### ISSUE THREAD

**Issue by rdowinton** [scrapinghub/portia#143]
The error below occurs when trying to annotate [this page](http://rateyourmusic.com/release/album/stan_getz/sweet_rain/):
```
/app/slyd/slyd/annotations.py:228 in apply_annotations
227                        continue
228                if int(last_id) < int(aid):
229                    if '__added' not in element.attributes:
exceptions.TypeError: int() argument must be a string or a number, not 'NoneType'
```
This problem seems to affect all other album pages on the website too. @ruairif mentions this is most likely an encoding issue.

**Comment by ruairif** [comment]
I've published a possible fix for this on the develop branch. You can access it from staging
