### ISSUE TITLE
unexpected internal error: Unterminated string

### ISSUE THREAD

**Issue by flip111** [scrapinghub/portia#145]
In red characters:
`unexpected internal error: Unterminated string starting at: line 1 column 61 (char 60)`

I have no clue what additional debug information i could provide other then i'm using the latest portia version on ubuntu 14.04 on python 2.7.6

It would be helpful if the original text which cause the error could be showed. I'm not sure _which_ text that is but i'm refering to the text referenced by `line 1 column 61 (char 60)`.

**Comment by ruairif** [comment]
Which website were you scraping at the time? Did any more information show up in your console along with the error?

**Comment by flip111** [comment]
My entry point is here http://www.pararius.nl/huurwoningen/amsterdam then i clicked to this page http://www.pararius.nl/appartement-te-huur/amsterdam/PR0001193393/entrepotdok

console shows this error:
![image](https://cloud.githubusercontent.com/assets/2244480/6390700/d70729fa-bdae-11e4-90d5-30adc8eb7118.png)

**Comment by ruairif** [comment]
Can you delete the generated annotation? (The one you made by selecting text be clicking and dragging the mouse)

**Comment by flip111** [comment]
I couldn't quite get to edit the original template ... so i made a new one selecting the same stuff except `exclusief`. All went fine. After that i, again, made a new template now with selecting `exclusief` and i see the error.

**Comment by ruairif** [comment]
I'm currently working on this as part of #133. Do you think you can select the element and use a regex extractor until it's fixed?

**Comment by flip111** [comment]
Yes sure. What about when an error occurs we can see the text for diagnose?

**Comment by ruairif** [comment]
That text is a catch all for errors, it's just there to help track down the issue.
Fixing the error usually involves repeating the steps with the debugger running. In this case it's probably something to do with how your data was saved but I won't know exactly what without checking it out.
