### ISSUE TITLE
Template used on wrong page

### ISSUE THREAD

**Issue by flip111** [scrapinghub/portia#148]
My start page has a list of products. The product detail page URL's have a specific format. I made a template for the product detail page. This template has a variant field on a `UL -> LI` list. The template matches some information on the product list page which i don't want. Which strategy should i choose to resolve this problem?

A few things that come to mind:

* Setting a dummy field on the product detail page to `-just required-`. Of an element that is not in the product list page.
* Match a specific extractor to a URL follow pattern.
* Exclude the start page with a no-follow pattern
* ???

I don't see a a clean, straight forwarded way to do this, so i'm not sure what is best practice here.

**Comment by ruairif** [comment]
I would go with `- just required -` myself. I don't think the other
solutions you've mentioned would work.
The other solution that would work would to be to write a middleware in
python to get it to ignore the item.

**Comment by flip111** [comment]
Thank you very much for your answer. Would it be an idea to move some of the README stuff to wiki pages? (example)[https://github.com/TryGhost/Ghost/wiki]

**Comment by ruairif** [comment]
The idea is to split it into different sections and display it on
readthedocs.org like other scrapinghub projects.
Feel free to split it into different pages on the wiki if you like though.
