### ISSUE TITLE
[Question] how store downloaded data to mysql? Is there  detailed document reference？

### ISSUE THREAD

**Issue by maoouyang** [scrapinghub/portia#149]
I have crawled store data to json file ,But I want to store it to my database. I have read the document of README.txt ,but I failed to connect my database . I am a first visitor for scrapy or portia ,so I want a detailed document so that I can achieve my Demand，thanks!!!

**Comment by ruairif** [comment]
There is currently no detailed tutorial available for how to do this.
If you want to go ahead without too much direction, the steps involved are:
* Creating your database tables
* Creating a pipeline that adds items to your database
* Adding that pipeline to your spider (edit ITEM_PIPELINES in YOURPROJECT/settings.py)

An example of a pipeline to save to MySQL can be found [here](https://github.com/darkrho/dirbot-mysql/blob/master/dirbot/pipelines.py#L36), you can customise that to suit your needs.

**Comment by maoouyang** [comment]
ok,I will try it soon. Now I am trying to crawl a Travel website。 But some data created By javascript, So these data cant be scraped ,Because some element of data is Invisible In the page when opened in portia .   could you help me scrape  this kind of data .

**Comment by ruairif** [comment]
This needs JS and there is currently no support for handling this in Portia.

**Comment by maoouyang** [comment]
So that!! other question,when I input a long url ,the long url cut off so that the portia cant visit the long url page! is it bug?

**Comment by ruairif** [comment]
I just isn't shown fully in the UI it should work with all long URLs that are less than 2000 characters

**Comment by maoouyang** [comment]
okay! About js problem,Whether it provides extension interface so that programming can solve it own.I think it is neccessay。

**Comment by maoouyang** [comment]
the portia can solve most Crawl issues，but I dont know how to solve some details ,such as 'request json' or 'js created' etc. That is to say ,if there is  program extension interface ,portia is perfect.has it?

**Comment by ruairif** [comment]
There are many ways to extend Portia. If you look at [Scrapy](http://doc.scrapy.org/en/latest/) (which the Portia spider is based on) you can see how to add pipelines (you can save to MySQL using those) and middlewares (which allow you to perform additional requests if needed). You can also try to use Portia with [Splash](http://splash.readthedocs.org/en/master/) to download pages and output the html after JS processing has finished. At the moment we are in the process if building new way to extend Portia which will make it possible to annotate and extract data in new ways which may be specific to your project.
