### ISSUE TITLE
No Such Resource

### ISSUE THREAD

**Issue by mediix** [scrapinghub/portia#151]
Hi everyone, 

Has anyone gotten this response: "No Such Resource File not found" back calling on this URL: http://localhost:9001/static/main.html.
After couple of hours struggling I finally got Portia working on my Linux box(Ubuntu 14.04) using virtualenv.
The python command line scripts are in place:
 $ head -1 `which twistd`
#!/home/mediix/.virtualenvs/portia/bin/python

I was able to get this output running "pip freeze -l" within my virtualenvironment:
$ pip freeze -l
cffi==0.9.1
characteristic==14.3.0
cryptography==0.8
cssselect==0.9.1
dulwich==0.9.7
enum34==1.0.4
jsonschema==2.3.0
loginform==1.0
lxml==3.4.1
mysql-connector-python==1.2.3
numpy==1.9.2
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycparser==2.10
pyOpenSSL==0.14
queuelib==1.2.2
requests==2.5.1
rfc3987==1.3.4
scrapely==0.12.0
Scrapy==0.24.4
service-identity==14.0.0
six==1.9.0
slybot==0.9
Twisted==14.0.2
w3lib==1.11.0
zope.interface==4.1.2

I was wondering if anyone on a linux box ran into this issue before could throw some help out here.

**Comment by ruairif** [comment]
Solutions [here](https://github.com/scrapinghub/portia/issues/150#issuecomment-77744437)

I pushed the wrong code to the master branch last week. I'll fix it either today or tomorrow depending on the stability of the develop branch
