### ISSUE TITLE
No page loaded eror

### ISSUE THREAD

**Issue by muhammedabuali** [scrapinghub/portia#152]
I just got started with partia. I am running portia locally and when I type the a url in the url box I get no page loaded error

some of ther urls I tried include

* www.google.com
* google.com
* https://medium.com/

**Comment by muhammedabuali** [comment]
@ruairif

**Comment by ruairif** [comment]
I'm going to need logs from your console, portia server and what commit you're on to help you.

It works for me for medium and google.

**Comment by gianpaj** [comment]
Where are the logs located?
I'm getting the same issue after a new installation with Vagrant.

No errors in the Chrome developers console. 
`wget google.com` works after ssh'ing in the vagrant VM...

I this the only process that needs to be running?
```
$ ps aux | grep slyd
root     14818  0.2  7.9  62900 40448 ?        Ssl  21:22   0:02 /usr/bin/python /usr/local/bin/twistd -n slyd -p 8000
```

commit: e9a80777339a84a34579dc3f68918cd216dc907f

**Comment by ruairif** [comment]
Did you try clicking on the link in the start pages on the left to get the page to load?

**Comment by muhammedabuali** [comment]
@ruairif  yes you are right. that did work! thanks
