### ISSUE TITLE
problem with installation 

### ISSUE THREAD

**Issue by mezuqu** [scrapinghub/portia#153]
I have installed to local (to be honest to my remote aws) however, due to a developers mistake, when i open failed to open main.html

However, i did 

tried both solution 1) and 2) by doing

/path/portia/ $ git reset --hard c49c060aadcc33ec85a2e768d48214fbd2612aa0

having:

fatal: Not a git repository (or any parent up to mount point /MY_PATH)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

2) tried to clone developed branch by git clone https://raw.githubusercontent.com/scrapinghub/portia/develop/ 
No luck. (had to look deeper to cloning other branches maybe)

3) It has been 2 days already, so could you please merge the latest version so that we can install it properly?

Thanks!

**Comment by ruairif** [comment]
I haven't merged as I found another bug related to renaming spiders.

For 1: you are either in the wrong directory or you copied the files rather than cloned the repository

For 2 try:
    git clone -b develop https://github.com/scrapinghub/portia

**Comment by ruairif** [comment]
Develop has been merged into master
