### ISSUE TITLE
Performance drawbacks using installations like vagrant/docker etc

### ISSUE THREAD

**Issue by mezuqu** [scrapinghub/portia#154]
May I ask why do you guys ask people to install the software within a docker or vagrant container, as they are a middleware, which recudes ram and cpu usage?

I am sure many of people want to install this great software to remote for bigger purposes where they might need more ram and CPU.

Thanks

**Comment by ruairif** [comment]
They make it easier to install if you have no experience with installing python software.

You can deploy it to many different cloud providers using Docker or Vagrant without much hassle.

The RAM and CPU usage for portia should be quite small.
