### ISSUE TITLE
Problem : how to override settings.py for each crawler

### ISSUE THREAD

**Issue by mezuqu** [scrapinghub/portia#156]
Hello,

There are some problems that i cant pass to the porticrawler using "-s" input. Like adding middlewares or item_pipelines. The reason I am doing this is to use a some special features of scrapy.

I tried to change scrapy.cfg, the scraper doesnt read anythhing from it. (from path/projects/mywebsite.com/

and tried to change path/projects/spiders/settings.py

However no luck. I.e. I want to change the USER_AGENT to something else . Is there a way to access to the right settings of scrapy so that I can manipulate?

Thanks

**Comment by ruairif** [comment]
You can edit it on a per project basis by editing (or adding of it doesn't
exist) a settings.py file to the root folder of your project. You can also
add middlewares and pipelines by adding a local_slybot_settings.py file to
/slybot/slybot.

**Comment by mezuqu** [comment]
editing files in settings.py doesnt change the situation. Only it accepts paramaters from cmd line.

**Comment by ruairif** [comment]
Can you submit a pull request that fixes this?
