### ISSUE TITLE
weird problems when i change the project name/spider name

### ISSUE THREAD

**Issue by mezuqu** [scrapinghub/portia#157]
There are some times that when I configure a crawler and start it, it doesnt work (and the web gui doesn't show up the items scraped) . 

It generally occurs, when I try to change the project name and/or spider name.

**Comment by ruairif** [comment]
Issues has been fixed with this commit: https://github.com/scrapinghub/portia/commit/d58d9bf51814f81cf7cbd120887c6747c52830ec
