### ISSUE TITLE
question : how to scrape varied elements

### ISSUE THREAD

**Issue by mezuqu** [scrapinghub/portia#158]
When I try to crawl a website, in some product page its like:

Productname:
Categoy1
Category2
Category3
Category4

And some products have listed about 2 categories.

In this case, i am adding variants for each category, is it a safe method to do it? Or I thought that portia's smart capabilities let us to train it, and it will scrape other category names if we assing an item to "caregory1" with variant1 and the others will be fetched automagically?
Thanks

**Comment by ruairif** [comment]
If you add variants to the top one and bottom one it might extract all of
them depending on bow the page is structured.
