### ISSUE TITLE
Crawler craws more than expected

### ISSUE THREAD

**Issue by mezuqu** [scrapinghub/portia#159]
When i start the crawler i set a CLOSESPIDER_ITEMCOUNT=5 (in which I see that the config is assigned) , however when the crawler finished it crawls more than 5, which is not expected.

Result from log file:
 'finish_reason': 'closespider_itemcount',

Is there a special reason for that?

**Comment by ruairif** [comment]
It had already made the requests to additional pages so it finished extracting from those before shutting down.
