### ISSUE TITLE
bug : DEPTH_LIMIT problem

### ISSUE THREAD

**Issue by mezuqu** [scrapinghub/portia#161]
I started portiacrawler iwth depth_limit to 3. however it ignores some urls. 

2015-03-12 06:44:48+0000 [www.MYWEBSITE.com] DEBUG: Ignoring link (depth > 3): http://www.MYWEBSITE.com/product-category.html 

As it's depth is not 3, only 2. What might be the problem

**Comment by ruairif** [comment]
The link was probably crawled from one of depth 2.

If you have questions rather than bugs can you direct them to the [forum](https://groups.google.com/forum/m/#!forum/portia-scraper) as you are causing noise in the issue tracker

**Comment by mezuqu** [comment]
Actually it is not. 

2015-03-18 06:59:00+0000 [mycrawler] DEBUG: Ignoring link (depth > 2): http://www.mysite.com/category1.html

I added http://www.site.com/category1 as the start url. so it doesnt crawl depth 1 from a depth 2. 
My intention is not here to make noise :) Please do not misunderstand me.
