### ISSUE TITLE
Saving Spider is stucked

### ISSUE THREAD

**Issue by mezuqu** [scrapinghub/portia#162]
There is very strange problem.

Crawler opens some of the URLS as normal, but some of the URLS not (the pages are very SIMILAR, and I controlled required feeds)

When i click to the pages for "annotate this page" it stucks on "saving spider". (it creates some random extractors somehow)

I am using latest ver. of chrome.

(I would like to give the url of my portia instance if asked in private, server is not mine :) )

**Comment by mezuqu** [comment]
I want to add, annotate this page doesnt show up.

**Comment by ruairif** [comment]
Which version of Portia are you using? I may need the URL to recreate the issus

**Comment by mezuqu** [comment]
@ruairif how I may send you the private URL?

**Comment by ruairif** [comment]
Why can't you post it here? I'm sure almost everybody using Portia are using it to scrape sites that aren't their own.

**Comment by ruairif** [comment]
Need more information to track down bug. Will reopen if information provided.
