### ISSUE TITLE
Neither Vagrant nor locally run Portia loads initial view when adding site

### ISSUE THREAD

**Issue by birt** [scrapinghub/portia#163]
I tried both the Vagrant version as well as the locally run version in a virtualenv.

My problem is this: when I add a site, it doesn't load the initial preview in the frame.
Everything else is confirmed working:
- I clicked on Test Spider while tcpdump'ing outgoing port 80 traffic. Requests are going out
- running the spider manually with portiacrawl shows it's doing its work as expected

Any ideas what might be causing the preview in the frame to fail?

I'm using FF on Linux - should I try another browser/OS combo?

**Comment by ruairif** [comment]
What does it say in your web console when you try to load the page?

**Comment by birt** [comment]
It says 'No page loaded'..

**Comment by birt** [comment]
Also, refresh button isn't enabled so I can't refresh...
tried it on slashdot.org

is the twisted port 9001 the only one needed? because I'm trying this over an ssh tunnel...

**Comment by ruairif** [comment]
This is the same problem people had in #152. You just need to click the link in the start urls.

I've recognised that this is an issue and a fix has been pushed to the develop branch to auto load the page. https://github.com/scrapinghub/portia/commit/2c6b2ecb510253e641c28c22498c1f295e14cbec
