### ISSUE TITLE
wrong setup.py

### ISSUE THREAD

**Issue by vit-tucek** [scrapinghub/portia#165]
When I try to deploy using scrapyd-deploy I get an error which occurs because the uploaded egg file doesn't contain the directory with templates. I suspect that's because setup.py of my data project forgets to mention it. I tried deleting it and let scrapyd-deploy create the setup.py file on it's own, but that didn't help.

**Comment by ruairif** [comment]
If you change your setup.py to this:

# Automatically created by: slyd

    from setuptools import setup, find_packages

    setup(
        name         = 'new_project',
        version      = '1.0',
        packages     = find_packages(),
        package_data = {
            'spiders': ['*.json', '*/*.json']
        },
        data_files = [('', ['project.json', 'items.json', 'extractors.json'])],
        entry_points = {'scrapy': ['settings = spiders.settings']},
        zip_safe = True
    )

It should work. If it does I'll fix the default `setup.py` template in Portia when I get a chance.

**Comment by ruairif** [comment]
@vit-tucek Did this work for you?

**Comment by vit-tucek** [comment]
Yes, it works. Thank you.
