### ISSUE TITLE
RegEx in Crawling

### ISSUE THREAD

**Issue by SophiaCY** [scrapinghub/portia#166]
Hi, recently I have met a problem:
I want to scrape pages like
 http://bbs.chinadaily.com.cn/home.php?mod=space&uid=174495&do=friend&from=space&page=2
 http://bbs.chinadaily.com.cn/home.php?mod=space&uid=174495&do=friend&from=space&page=9
 http://bbs.chinadaily.com.cn/home.php?mod=space&uid=234443&do=friend&from=space&page=2
Just the uid numbers and the page numbers are changed.
So I'd like to know how to write RegEx in Crawing so that only the  links that match this patterns can be followed.
![_2015-03-17t13-29-55 511z](https://cloud.githubusercontent.com/assets/10937666/6688369/b7cc5cce-cced-11e4-918e-dae38b4dc38b.png)

I have tried to write the RegEx like 
http://bbs.chinadaily.com.cn/home.php?mod=space&uid=(\d*)&do=friend&from=space&page=(\d*)
But it did work because the color was red.
![_2015-03-17t13-38-14 955z](https://cloud.githubusercontent.com/assets/10937666/6688445/472ac0cc-ccee-11e4-84d8-a58335016778.png)

Thanks a lot!

**Comment by okey** [comment]
You need to escape some characters that have special meaning in a regular expression. In the regex box, add a backslash in front of characters like `.`, `/`, and `?`.

This should work:

    http:\/\/bbs\.chinadaily\.com\.cn\/home\.php\?mod=space&uid=\d+&do=friend&from=space&page=\d+

**Comment by ruairif** [comment]
You don't need to include the whole URL. Something like the following regex should work:

    home\.php.*uid=\d*.*page=\d*

**Comment by SophiaCY** [comment]
Thank you very much! @okey  @ruairif
