### ISSUE TITLE
portia-web JS 404ing

### ISSUE THREAD

**Issue by BenChirlin** [scrapinghub/portia#167]
I've tried setting up portia locally using both Vagrant _and_ virtualenv with identical results: the portia-web JS file 404s. I'm guessing this is the main script for the app since all I get is an empty page with the title set to 'Portia'.

The file it's specifically looking for is `http://localhost:9001/assets/portia-web-2d8f47582c607b2eb425c27181aa89ee.js`

Is there some Gulp process or something I need to run? What am I missing here?

**Comment by mezuqu** [comment]
the latest version is not stable. sam problem with local installation.

**Comment by andypmw** [comment]
Facing same problem here... Im using vagrant on my Ubuntu

![error-portia](https://cloud.githubusercontent.com/assets/2743194/6704401/5ad59ef8-cd7a-11e4-8510-8732e0432c96.png)

**Comment by andypmw** [comment]
After checking some closed issues, I have idea to pull the develop branch.

So for temporary fix, go to portia repo directory and then type : 

```sh
$ git checkout develop
$ git pull origin develop
```

Voila, Portia loaded!

![fixed](https://cloud.githubusercontent.com/assets/2743194/6704772/e61c3986-cd7f-11e4-80a4-6c9749c0f256.png)

**Comment by ruairif** [comment]
The assets weren't updated on the master branch. I've fixed this now.

If you need to recompile the assets you can do the following (taken from the Dockerfile):

    sudo npm install bower ember-cli -g
    cd portia/slyd
    npm install
    bower install
    ember build -e production
