### ISSUE TITLE
Test spider doesn't extract data of newly added fields until you leave the spider page

### ISSUE THREAD

**Issue by jskrill** [scrapinghub/portia#168]
Steps to reproduce:

1. Annotate a page
2. When an element is selected, create a new field and assign the annotation to that field
3. Save template
4. The newly annotated data will not be extracted from the page when you click Test Spider

If you leave the spider's page and then return Test Spider will have the new field properly extracted. The template seems to still match the page even though the extracted data isn't being shown.

**Comment by ruairif** [comment]
The item isn't being updated in the spider controller until the data is reloaded with a page change.

The controller needs the item [here](https://github.com/scrapinghub/portia/blob/master/slyd/app/controllers/spider.js#L223) to update what extracted fields are displayed.

Do you want to attempt a fix?

**Comment by jskrill** [comment]
Sure

**Comment by ruairif** [comment]
Fixed by https://github.com/scrapinghub/portia/pull/170
