### ISSUE TITLE
Add a text box to filter by spider name

### ISSUE THREAD

**Issue by almeidaf** [scrapinghub/portia#17]
add a text box on top of the spider list to filter by name (usefull when you have a large number of spiders)

like in https://dash.scrapinghub.com/p/1131/jobs/ >Jump to > jump to spider

**Comment by ruairif** [comment]
Is this what you're after? It's currently available on dash.

![filter_spiders](https://cloud.githubusercontent.com/assets/6472969/5724338/cb245ca4-9b42-11e4-9978-8bd3debcb37d.png)

**Comment by almeidaf** [comment]
thats exactly what i was thinking
