### ISSUE TITLE
about links to follow 

### ISSUE THREAD

**Issue by BigAN** [scrapinghub/portia#172]
i give url http://ent.qq.com as start url and then click and annotate any one of this page. In crawling section , i click "configure follow and exclude patterns" and add "ent.qq.com/\w/\d+/\d+.htm" in FOLLOW LINKS area. Also , i click overlay blocked links. the result is as my expected.

my problem is that i click test spiders, no items are extracted. when i choose sub link of  http://ent.qq.com  as a start url ,it works well but still no links are followed. i can not figure out why. 

ps : where i can find the extracted data in storage.

**Comment by ruairif** [comment]
The Portia UI is only used to build the spider. To run the spider and extract the data you need to use the portiacrawl utility.

For more information look at the [running a spider](https://github.com/scrapinghub/portia#running-a-portia-spider) section of the readme
