### ISSUE TITLE
Possible Json output unicode problem

### ISSUE THREAD

**Issue by mezuqu** [scrapinghub/portia#175]
In scrapy, the default output for each file is utf8 format, however with portia, when i add -jsonline output, all I get iin the output file like pro\u4d31something . 

I think there is a formatting problem with output

**Comment by ruairif** [comment]
It makes it harder to read but it's still valid json, according to the [spec](http://json.org), so it's not really a problem.

**Comment by mezuqu** [comment]
problem is, I cant convert the data into readable format. Since the site crawling is in urf8 format, why does portia crawl and extract the data into the non-utf format? Is there an option where I can enable utf8?

**Comment by ruairif** [comment]
It uses the default json encoder included in scrapy. It extracts the data as utf-8 and escapes non utf-8 characters according to the spec.

If you really want to have them be readable you need to create a new exporter.
You can find information on exporters [here](http://doc.scrapy.org/en/latest/topics/feed-exports.html) and [here](https://groups.google.com/d/msg/scrapy-users/rJcfSFVZ3O4/ZYsD7CMoCKMJ)
