### ISSUE TITLE
Entering domain without protocol (e.g. http) results in unexpected string error

### ISSUE THREAD

**Issue by rdowinton** [scrapinghub/portia#179]
If you enter a domain without the protocol e.g. 'ikea.com' vs 'http://ikea.com' the following error occurs:

```
Server responded with error:

unexpected internal error: expected string or buffer
```
It would be better to display an error such as invalid URL or allow entering the domain only and default to http as the protocol.

**Comment by ruairif** [comment]
Where are you entering the domain?
It already adds http during spider creation and when adding urls.

**Comment by rdowinton** [comment]
Strange, I tried again and the page loaded without any error. I'm not sure what I did differently before, but I was able to reproduce it consistently at the time.

**Comment by ruairif** [comment]
Feel free to reopen this if it starts happening again.
