### ISSUE TITLE
setting up on windows

### ISSUE THREAD

**Issue by judaschrist** [scrapinghub/portia#18]
Hi guys, this is a really fascinating tool by description but i'm still struggling on getting it running on my windows8 x64
i have encountered problems like running twistd command in windows cmd, installing scrapy properly on x64 platform.
tackled some of them but still facing a lot other problems.

is it possible that the team can provide with a specific setting up guide for this tool on windows?

**Comment by ruairif** [comment]
More info is now available in the README about how to install it on different platforms
