### ISSUE TITLE
Regular Expressions not working

### ISSUE THREAD

**Issue by bgt-prabhakard** [scrapinghub/portia#180]
I am using regular expression in python-scrapy script to extract. But when I try to use that same regular expression for extracting the same content in Portia, its not working. Why Portia can't able to recognize the regular expressions as same as in python-scrapy script.

Is there any specific pattern for using regular expressions in Portia?

**Comment by okey** [comment]
Please provide some more details. An example of a regex which doesn't work as expected in Portia along with where and how you are trying to use it would be very helpful.

**Comment by bgt-prabhakard** [comment]
I am going to extract Date, Month and Year as individual items from the following 


<td align="center" class="cDate">28, March, 2015</td>


Initially I have annotated the tag "td" as Date to get "28" using regular expression "(.*?),.*"

Then I have paritally annotated the text "28, March, 2015" as Month to get "March" using regular expression ".*, (.*?),.*"

again I have paritally annotated the text "March, 2015" only as Year to get "2015" using regular expression ".*, (.*?)"

But if I give continue browsing after finishing annotations I am getting only "Date" item but not Month and Year

Is this because of regular expression or the Partial annotations?

**Comment by ruairif** [comment]
There is no  way to get all 3 pieces of data this way at the moment.

Does it need to be in separate fields or would it be suitable if you could have the data in the form `2015-03-28`?

**Comment by bgt-prabhakard** [comment]
Date needs to be separate fields as I want to filter-out based on Date or Month.
Is it possible to convert the date "28, March, 2015" into  "2015-03-28" in Portia?
Can we able to replace a text with another?

**Comment by ruairif** [comment]
It's not possible at the moment but it wouldn't take much to add support for it.

If you really need it in separate fields you could split the text with a pipeline.
