### ISSUE TITLE
Setting default value for a field

### ISSUE THREAD

**Issue by bgt-prabhakard** [scrapinghub/portia#181]
Is it possible to set a default value for a field in Portia?
Ex:
   I am going to extract name, price and company for a product in a retail website. If name and price are available and company is not available/empty, how can I set the default text as "Unknown" in that company field.

**Comment by ruairif** [comment]
There is currently no way to do this through the UI but this task is commonly carried out using [Scrapy pipelines](http://doc.scrapy.org/en/latest/topics/item-pipeline.html)

If you are using `portiacrawl` you can enable a pipeline by having it available in your python path and then adding it to a `portia/slybot/slybot/local_slybot_settings.py` file as described in the link above
