### ISSUE TITLE
i have this problem "unexpected internal error: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by krelfallahhichem** [scrapinghub/portia#182]
when i write a new project in URL like this "http://localhost:9001/static/main.html#/projects/myproject"
and after write start URL , portia display this error "unexpected internal error: 'NoneType' object is not iterable"  
i need help thanks.

**Comment by ruairif** [comment]
What start URL are you using so that I can try to replicate the error?

**Comment by krelfallahhichem** [comment]
the start URL is "www.it-ebooks.info" ,  i try other URL and the same problem

**Comment by ruairif** [comment]
I can't recreate your issue. Are you using the latest version of Portia? Have you tried creating a new Portia project and using the url in the project?

**Comment by krelfallahhichem** [comment]
yes i use the latest version of portia 
i tried creating a new project and using the URL , its running normaly
but i need to create the project via URL of browser like this "http://localhost:9001/static/main.html#/projects/myproject"

**Comment by richardpenman** [comment]
I often experience this same error in the latest version when start a project and then click a URL.
