### ISSUE TITLE
  Bug with Scrapy 0.25.0-298-g5846d61

### ISSUE THREAD

**Issue by OlgaCh** [scrapinghub/portia#184]
After upgrade on dash both deploy and spiders scheduling stopped to work and failed with the message:
>
>    Traceback (most recent call last):
>    File "/usr/lib/pymodules/python2.7/scrapy/cmdline.py", line 142, in execute
>    cmd.crawler_process = CrawlerProcess(settings)
>    File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 123, in init
>    super(CrawlerProcess, self).init(settings)
>    File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 77, in init
>    self.spiders = smcls.from_settings(settings.frozencopy())
>    File "/tmp/eggs-RzTd6X/main.egg/enclarity/spidermanager.py", line 21, in from_settings
>    o = super(EnclaritySpiderManager, cls).from_settings(settings)
>    File "/usr/lib/pymodules/python2.7/slybot/spidermanager.py", line 34, in from_settings
>    return cls(datadir, spider_cls, settings=settings)
>    File "/usr/lib/pymodules/python2.7/slybot/spidermanager.py", line 22, in init
>    settings.set('PLUGINS', load_plugins(settings))
>    File "/usr/lib/pymodules/python2.7/scrapy/settings/init.py", line 92, in set
>    self.assert_mutability()
>    File "/usr/lib/pymodules/python2.7/scrapy/settings/__init_.py", line 115, in _assert_mutability
>    raise TypeError("Trying to modify an immutable Settings object")
  >  TypeError: Trying to modify an immutable Settings object

**Comment by ruairif** [comment]
Fixed by https://github.com/scrapinghub/portia/commit/75f5ee54093b88e7d22a800e8289238d3903cf18
