### ISSUE TITLE
big text input for start urls

### ISSUE THREAD

**Issue by kalessin** [scrapinghub/portia#19]
Usually the user needs to enter a large list of start urls for a given spider. The current interface only allows to add them one by one, which is more impractical for bigger list of start url.

We need a way to allow to copy/paste a list of start urls, one per line. This does not mean to remove the one by one method, but just to add the alternative to open a big text box to copy them inside.

**Comment by patange1996** [comment]
> Fixed on dashintegration branch

@ruairif Can you provide more details on how I can get information on this issue?
I want a big text input for start urls on my project but I am unable to find any solution. This might help if you tell me where I can find the answer?
