### ISSUE TITLE
No module named slybot.settings

### ISSUE THREAD

**Issue by suicid3** [scrapinghub/portia#190]
The documentation is extremely vague for someone just stepping in. But after about 14 hours of fumbling around I've gotten far enough that my project wants to launch, but gets the above error. I can't seem to find any information on getting around this. Here's an output of what I got so far (using local virtualenv install on Ubuntu 14.04 x86_64)

```
root@Admin-Ubuntu-Gnome:/home/admin/virtualenv/MyProject/portia/slybot/bin# portiacrawl /home/admin/virtualenv/MyProject/portia/slyd/data/projects/new_project_1 MyProject.com -set -t csv -o project_test.csv

Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 109, in execute
    settings = get_project_settings()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/project.py", line 60, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 109, in setmodule
    module = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named slybot.settings
```

Any help is more than appreciated.

**Comment by ruairif** [comment]
If you open a terminal and run:

    import slybot
    slybot.__version__

What version is it using?

**Comment by suicid3** [comment]
I get nothing from those. Is the a specific directory I need to be in to run that?
This is the output
```
root@Admin-Ubuntu-Gnome:/home/admin/virtualenv/MyProject/portia/slybot/bin# import slybot
bash: /usr/bin/import: No such file or directory

root@Admin-Ubuntu-Gnome:/home/admin/virtualenv/MyProject/portia/slybot/bin# slybot.__version__
slybot.__version__: command not found
```

**Comment by ruairif** [comment]
You need to run them inside a python shell

**Comment by suicid3** [comment]
I'm pretty sure I'm missing something here. Just not sure exactly what it is....here's what I get inside python shell....

```
>>> import slybot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named slybot
>>> slybot.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'slybot' is not defined
```

**Comment by suicid3** [comment]
Python details - 
```
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by ruairif** [comment]
You haven't installed Portia properly then.
Follow the install instructions in the Readme

**Comment by suicid3** [comment]
Creating a new VirtualEnv and trying again, Here's a question that just crossed my mind. The missing dependancies, will those need to be installed into the virtualenv or will they be used from the system install? I appreciate your help. Love the interface by the way.

**Comment by ruairif** [comment]
They will be installed into the virtualenv. It's possible that you are missing a few libraries for the install to run successfully. Make sure you install them if the `pip install -r requirements.txt` fails.

**Comment by suicid3** [comment]
I got errors before but it doesn't look like anything failed this time around :)

**Comment by suicid3** [comment]
Okay, found the issue. I wasn't activated in the virtualenv when I was trying to run the crawler.
Anyone else who may come across this struggling with it to work and the right directories and all - here's my overnight of notes in a condensed version - works flawless now :)
```
#INSTALL PORTIA
sudo apt-get install libxml2-dev libxslt-dev python-dev zlib1g-dev libffi-dev libssl-dev
cd /home/user_name
mkdir Portia_Crawler
cd Portia_Crawler
virtualenv Portia_Env --no-site-packages
source Portia_Env/bin/activate
cd Portia_Env
git clone https://github.com/scrapinghub/portia.git
cd portia
pip install -r requirements.txt
pip install -e ./slybot

#START PORTIA VISUAL EDITOR
cd /home/user_name/Portia_Crawler
source /home/user_name/Portia_Crawler/Portia_Env/bin/activate
cd /home/user_name/Portia_Crawler/Portia_Env/portia/slyd
twistd -n slyd

#OPEN BROWSER TO PORTIA
http://localhost:9001/static/index.html

#RUN CRAWLER
#
#CTRL+ALT+T for NEW TERMINAL
#
source /home/user_name/Portia_Crawler/Portia_Env/bin/activate
cd /home/user_name/Portia_Crawler/Portia_Env/portia/slybot/bin
portiacrawl /home/user_name/Portia_Crawler/Portia_Env/portia/slyd/data/projects/new_project myProject.com -t csv -o /home/user_name/Desktop/SaveFile.csv
```
