### ISSUE TITLE
Usage of Regular Expression for current page URL

### ISSUE THREAD

**Issue by bgt-prabhakard** [scrapinghub/portia#191]
I want to extract the specific content from the current page URL using Regular Expression.
Ex: https://github.com/scrapinghub/portia/issues/190
https://github.com/scrapinghub/portia/issues/184
https://github.com/scrapinghub/portia/issues/175

If Suppose, I am trying to annotate the above URLs and I need to save the the above URL in one Field and also I want to store the numbers 190,184 and 175 in another field from those URLs using regular expressions

How can I do that in Portia?

**Comment by ruairif** [comment]
You would need to write a pipeline that extracts the number using a regex and adds it to a new field in the extracted item.

**Comment by bgt-prabhakard** [comment]
For using regex I have to write a pipeline, that is for deployment. Is it possible to make this option available in Portia UI?
How can I save the current page URL in a Field?

**Comment by ruairif** [comment]
Pipelines provide a way to add additional functionality to your spiders using python code.
The URL is saved by default in the `url` field so you can access it with a pipeline.

**Comment by bgt-prabhakard** [comment]
Is it possible to save that URL in customized field other than "url" field in Portia UI itself?

**Comment by ruairif** [comment]
No. If it is not available in the page then it can't be extracted without a pipeline.

The id number you're looking for might be available in a metatag or somewhere else on the page
