### ISSUE TITLE
Add date extraction support

### ISSUE THREAD

**Issue by ruairif** [scrapinghub/portia#192]
Date is a common data type that people wish to extract but this currently isn't supported by portia.
It could be possible to add support for this by using the [dateparser](https://github.com/scrapinghub/dateparser) library.

**Comment by baswillems** [comment]
Thanks, this would be awesome and help me a lot!

**Comment by shaneaevans** [comment]
In order for this to work well, we may need to add support to dateparser to allow dates embedded in other text, for example:

```python
>>> dateparser.parse("April 24th")
datetime.datetime(2015, 4, 24, 0, 0)
>>> dateparser.parse("opens April 24th")
>>>
```

**Comment by ruairif** [comment]
@shaneaevans It can be used with partial annotations in those cases for now.

**Comment by Allactaga** [comment]
I don't think that `dateparser` would be solution here as it focuses on multilingual support and expects **valid** dates. We had fuzzy parsing earlier, but it only introduced problems for other languages and we eventually cut it out.

**Comment by ruairif** [comment]
Basic date support without fuzzy matching has been added.
