### ISSUE TITLE
Support for JS

### ISSUE THREAD

**Issue by shaneaevans** [scrapinghub/portia#2]
Add support for JS based sites. It would be nice to have UI support for configuring instead of having to do it manually at the Scrapy level.

Perhaps we can allow users to enable or disable sending requests via [Splash]( https://github.com/scrapinghub/splash).

**Comment by maoouyang** [comment]
So that!! other question,when I input a long url ,the long url cut off so that the portia cant visit the long url page!  is it bug?

**Comment by robertkeizer** [comment]
So much yes in this.

I'll be taking a look through this seeing how far off it is.

**Comment by bgt-prabhakard** [comment]
Is it possible to support JS by Portia by using splash?

**Comment by agramesh** [comment]
Hi i use this mechanism for javascript urls

DOWNLOADER_MIDDLEWARES = {
    'xxxxxx.middleware.splash.SplashMiddleware': 725,
}

SPLASH_ENABLED = True
SPLASH_ENDPOINT = 'http://localhost:8050/render.html'
SPLASH_WAIT = 2
SPLASH_IMAGES = False
SPLASH_URL_PASS = (r'www.xxxxxxx.com',)
#SPLASH_URL_BLOCK = (r'badexample\.com',)

CONCURRENT_REQUESTS_PER_DOMAIN = 1
CONCURRENT_REQUESTS = 16


- I didnt receive javascript enable error, portia is continuously loading the url without end, but in command prompt error load as 
    --- <exception caught here> ---
      File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/home/test/portia-master/portia-master/slyd/slyd/bot.py", line 97, in fetch_callback
        request = response.meta['twisted_request']
    exceptions.KeyError: 'twisted_request' 

- is anything possible to solve this please reffer.

**Comment by ruairif** [comment]
It's possible that the middleware is accidentally removing the `twisted_request` object which is used to return the results from the spider. If you find where it's doing that and make sure it doesn't get removed then it should work.

**Comment by agramesh** [comment]
Hi is there any updates in new release of portia for javascript urls, still i have some error to configure the above mechanisms.

**Comment by agramesh** [comment]
Hi anybody have  the reference for portia-splash middleware

**Comment by ruairif** [comment]
What do you mean by reference?

**Comment by agramesh** [comment]
I used scrapinghub splash middleware but its not working for javascript in portia , the above mechanism I mentioned is work perfect but i receive empty pages from portia ui, so i think the middleware is not support, can you suggest any idea  for this

**Comment by ruairif** [comment]
Did you try adding the middleware to `slybot/slybot/settings.py`?

**Comment by agramesh** [comment]
i tried in  slyd/slyd/settings.py, there i create a local_settings.py file for above mechanism and import it to settings.py, is this correct? or please let me know how to configure it

**Comment by ruairif** [comment]
Try putting it in:
    
    /slybot/slybot/local_slybot_settings.py

**Comment by agramesh** [comment]
ok i will try and update with you, thanks

**Comment by agramesh** [comment]
i tried your suggestion "/slybot/slybot/local_slybot_settings.py" 
same error i received from portia ui, so please can u give any referrence url for  middleware
python file
