### ISSUE TITLE
Support to index tables?

### ISSUE THREAD

**Issue by fjorgemota** [scrapinghub/portia#20]
Hello.

I'm testing Portia and I found that there is none actual way to index a table.

By 'index a table', I think something like allowing a element with various parents (something like `table > tr (which can vary) > td` based on a determinated index, or something like it).

I think that, for some cases, this is useful, like for indexing a page with tables. However, I not tested Slybot to see if it support that feature. 

Can anyone help?

Thanks

**Comment by aleafboat** [comment]
can you give me a demo of Portia  that how to config
