### ISSUE TITLE
Improving number, price and geopoint extractors

### ISSUE THREAD

**Issue by ruairif** [scrapinghub/portia#212]
Number support in slybot is divided between price extraction and number extraction.
Number extraction works only on numbers that match the following:

```
-?\d+(?:\.\d+)?
```

Price extraction has some extensions to this but can sometimes result in incorrect output:

``` python
>>> from scrapely.extractors import extract_price
>>> extract_price('1,000,000')
'1000000'
>>> extract_price('1,000,000.00')
'1000000.00'
>>> extract_price('1,000')
'1000'
>>> extract_price('1000,00')
'1000.00'
 >>> extract_price('1,000.00')
'1000.00'
>>> extract_price('500,000.00')
'500000.00'
>>> extract_price('500.000,00')
'500.000'  # Should output '500000.00'
>>> extract_price('-500,000,00')
'500000.00'  # Should output '-500000.00'
>>> extract_price('500 000,00')
'500'  # Should output '500000.00'
```

Price extraction should be extended to support negative numbers along with support for guessing the correct separators used for thousands and decimals.

The geopoint within slybot doesn't provide any additional modification of the data that it receives.
This extractor should be improved to search for number combinations within the extracted data.
Common formats for geopoint data are:

```
12.34,3.53
12.34, 3.53
12.34 3.53
12.34;3.53
12.34;3.53
-12.34, +3.53
```

Geopoint data should be formatted and output in the format below:

```
12.34, 3.53
```

**Comment by kmike** [comment]
A pony request: it'd be nice for price to also handle 'out of stock' labels.

**Comment by satwikkansal** [comment]
Hi @ruairif I'd like to work on this issue. Could someone please assign me to this issue.

**Comment by ruairif** [comment]
@satwikkansal You can just fork the repo and make a PR referencing this issue. As @kmike mentioned please add support for assigning labels to values.

**Comment by harshasrinivas** [comment]
Scrapely's [Price extraction module](https://github.com/scrapy/scrapely/blob/master/scrapely/extractors.py) uses `(\d[\d\,]*(?:(?:\.\d+)|(?:)))` - which offers no support for negative numbers/separators.

So instead of using Scrapely, would you like a set of functions to be developed exclusively for Portia?
