### ISSUE TITLE
Rendering Javascript urls

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#215]
i load the url in portia, its shows the error like this, how could render this type of urls in portia

![java](https://cloud.githubusercontent.com/assets/11834931/8333245/c8111b14-1aaf-11e5-9c9a-42866a2b0ae7.jpg)

**Comment by Youwotma** [comment]
We are working at the moment in adding JavaScript support to Portia, unfortunately it's not ready yet, but you can follow the development and try it in the [js-support](/scrapinghub/portia/tree/js-support) branch.

**Comment by agramesh** [comment]
is it possible in portia to load the javascript urls through splash server, where to configure the splash server

**Comment by ruairif** [comment]
You can just run your own splash server. Then when you run the spider make sure that the `SPLASH_URL` setting points to your server

**Comment by agramesh** [comment]
after assign the url in portia UI, where the function run in script to load the url

**Comment by agramesh** [comment]
hi
I am checking in Portia JS-support, when I run a portia UI i receive following error,

ImportError: No module named resource

resource.py file not triggered here, how will rectify this

**Comment by ruairif** [comment]
The js-support branch has been merged into develop. Could you try using that branch and see if it works for you?

**Comment by agramesh** [comment]
is develop only configure for this, it will call js-branch?

**Comment by agramesh** [comment]
while running this command
 "twistd -n slyd"

i receive the error as
"ImportError: No module named resource"

**Comment by ruairif** [comment]
The instructions for running portia have changed. You now need to run the script in:

    bin/slyd

**Comment by agramesh** [comment]
I think from the splash request is stopped.
error shows as
"from splash.qtutils import qurl2ascii, REQUEST_ERRORS"
