### ISSUE TITLE
Due to installation error on portia master branch

### ISSUE THREAD

**Issue by dpcsuresh** [scrapinghub/portia#227]
I am getting the following error while running slyd server:

from slyd.bot import create_bot_resource
  File "portia-master/slyd/slyd/bot.py", line 26, in <module>
    from scrapy.crawler import CrawlerRunner
ImportError: cannot import name CrawlerRunner

**Comment by Youwotma** [comment]
Hi,

Please ensure that you have all the requirements installed:
```
pip install -r slyd/requirements.txt
pip install -r slybot/requirements.txt
```
To make this easier, you can also run portia inside docker:
https://github.com/scrapinghub/portia#running-portia-with-docker
