### ISSUE TITLE
How to store data in database

### ISSUE THREAD

**Issue by SophiaCY** [scrapinghub/portia#228]
Hi, I want to use MYSQL to process my data. 
    I have added a local_settings.py file in slyd/slyd and the bin/init_mysqldb script. 
    So what should I do next? How can I create a new table in the database and then store the scraped data into it?
    Thank you very much! Hope you reply soon;)

**Comment by ruairif** [comment]
If you want to store the data that you obtain while crawling you will need to create a pipeline to use with your spider.

There is currently no detailed tutorial available for how to do this.
If you want to go ahead without too much direction, the steps involved are:
* Creating your database tables
* Creating a pipeline that adds items to your database
* Adding that pipeline to your spider (edit ITEM_PIPELINES in YOURPROJECT/settings.py)

An example of a pipeline to save to MySQL can be found [here](https://github.com/darkrho/dirbot-mysql/blob/master/dirbot/pipelines.py#L36), you can customise that to suit your needs.

**Comment by SophiaCY** [comment]
So I should start from "class MySQLStorePipeline(object):" ? What should I import ? Thanks.

**Comment by SophiaCY** [comment]
BTW, how can I just scrape the data from the latest month? Thanks.

**Comment by SophiaCY** [comment]
Hi, I'd also like to know that what should I import in my pipelines.py, thanks.

**Comment by ruairif** [comment]
You need to create a spider middleware to tell the spider to stop when it has reached links that are older than a month old. It may also be possible to use `follow_urls` to tell it to only follow links that match `2015/07` or something like that.

To import your own pipelines.py you can edit the `settings.py` file in your project folder to add it there. You can find more info [here](http://doc.scrapy.org/en/1.0/topics/item-pipeline.html#activating-an-item-pipeline-component).
