### ISSUE TITLE
Reconnection to server freezes Portia

### ISSUE THREAD

**Issue by nestortoledo** [scrapinghub/portia#253]
Reloading from Portia doesn't work, requires a refresh in the browser

![screen shot 2015-08-20 at 1 46 13 pm](https://cloud.githubusercontent.com/assets/11273858/9434024/9f4912c0-49ff-11e5-8374-d29db09b046f.png)

**Comment by ruairif** [comment]
This has been fixed as far as we know. If it happens again please re-open this ticket.
