### ISSUE TITLE
We shall install splash for render javascript on windows?

### ISSUE THREAD

**Issue by dpcsuresh** [scrapinghub/portia#259]
We need to install splash for this master branch on windows.?

**Comment by ruairif** [comment]
When running the crawler you need to have an instance of Splash available. When building spiders you just need to run Portia. We recommend that you run Portia using either docker or vagrant. If you are able to install Portia directly on a windows system we would love to know what steps you followed so that we can add it to the documentation

**Comment by dpcsuresh** [comment]
Installed portia using following software on windows:
1. get-pip
2. Git-1.9.5-preview20150319
3. lxml-3.3.5.win-amd64-py2.7
4. python-2.7.6.amd64
5. pywin32-218.win-amd64-py2.7
6. Twisted-15.0.0.win-amd64-py2.7
7. VCForPython27

download portia.
after that we proceed following:

cd portia
pip install -r requirements.txt
pip install -e ./slybot

then start 
http://localhost:9001


I have installed portia when i try to start the slyd server i am getting following error on windows:

python c:\Python27\Scripts\twistd.py -n slyd

    from splash.qtutils import qurl2ascii, REQUEST_ERRORS
  File "C:\Python27\lib\site-packages\splash\qtutils.py", line 19, in <module>
    from splash.utils import truncated
  File "C:\Python27\lib\site-packages\splash\utils.py", line 9, in <module>
    import resource
ImportError: No module named resource

Thanks

**Comment by ruairif** [comment]
Unfortunately the `resource` module is unix specific. Maybe you could develop a patch for Splash to add windows support.

**Comment by dpcsuresh** [comment]
Can you please guide me how to develop a patch file for splash to add in windows support?

**Comment by ruairif** [comment]
You would need to modify some parts of splash until it works on windows. I don't have a Windows machine available at the moment so I can't help develop a patch. Have you tried installing Portia using Docker or Vagrant?

**Comment by dpcsuresh** [comment]
I have installed docker in windows. when i start docker in windows i am getting error
>boot2docker start
"error in run: Failed to start machine "boot2docker-vm": exit status 1"
where should be start docker in portia?
