### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#260]
- Hi while i running portia i received error like as
          from splash.utils import truncated
           File "C:\Python27\lib\site-packages\splash\utils.py", line 9, in <module>
            import resource
         ImportError: No module named resource
- after that i changed "from slyd import resource" like this in utils.py, but now i receive error from application\app.py like
       File "C:\Python27\lib\site-packages\twisted\application\app.py", line 451,
      createOrGetApplication
       ser.setServiceParent(application)
      AttributeError: Site instance has no attribute 'setServiceParent'
- How could it resolve

**Comment by Youwotma** [comment]
Hi,

Portia it's not tested on windows :) please use docker (instructions in the README) the vagrant (instructions in the README) or the [hosted version](http://portia.scrapinghub.com/)

If you want to make the effort to port it to windows, this problem sounds like a PYTHONPATH issue.

Regards,
David

**Comment by Youwotma** [comment]
Sorry, actually the issue seems to be that that module is unix-specifix, look in this other issue:
https://github.com/scrapinghub/portia/issues/259
