### ISSUE TITLE
Portia Test in ubuntu

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#270]
-I check the portia in Ubuntu os. actullay I use ubuntu 14.2   64 bit OS. 

pip install -r requirements.txt
pip install -e ./slybot

-these installation working fine. but 
sudo docker/splash.sh is shows error like this

Reading package lists...
Building dependency tree...
Reading state information...
netbase is already the newest version.
pkg-config is already the newest version.
python-qt4 is already the newest version.
ca-certificates is already the newest version.
xvfb is already the newest version.
libqt4-webkit is already the newest version.
libre2-0 is already the newest version.
libre2-0-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 355 not upgraded.
docker/splash.sh: 12: docker/splash.sh: zlib1g: not found

Usage:   
  pip install [options] <requirement specifier> ...
  pip install [options] -r <requirements file> ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --no-cache-dir

- if I run bin/slyd
  File "bin/slyd", line 3, in <module>
    import splash.server
  File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 9, in <module>
    from psutil import phymem_usage
ImportError: cannot import name phymem_usage

- is portia support in Ubuntu 14.2 or what OS support

**Comment by ruairif** [comment]
Your version or pip is out of date please upgrade it to a newer version or remove the --no-cache-dir from the docker.sh script.

Why not just run it in vagrant or docker as these are known to work with no issues?

**Comment by agramesh** [comment]
In ubuntu also have same issue 
#261
What is the installation steps of portia by docker and how run it in docker. is it open the locahost:9001?

**Comment by agramesh** [comment]
after adding path for slyd and slybot , then make a small change in slyd/bin/slyd file like this 
root = kwargs.get('root', DEFAULT_PORTIA_ROOT)
the portia javascript UI is working

**Comment by agramesh** [comment]
it can be run in localhost:9001.
thank you
