### ISSUE TITLE
Please let me know what procedure to follow by you to render javascript in your scrapinghub cloud?

### ISSUE THREAD

**Issue by PPSURESH** [scrapinghub/portia#271]
Hello everyone,

I have signup and create project in your scrapinghub dash board, Here i can able to render javascript in your cloud base using porita, but i cant able to redner javascsript using master branch in ubuntu os local . Please let me know what is the procedure to follow steps for render javascript to follow up.

kind and need
Thanks

**Comment by ruairif** [comment]
Do you have Portia running locally? Do you have a splash instance available to connect to?

**Comment by sureshcrescent** [comment]
Hello, We have not running porita using master branch as you told previous discussion,  also i am not having splash instance to connect with this.
