### ISSUE TITLE
Issue with `double encoding` with cyrrilic chars in start urls

### ISSUE THREAD

**Issue by Skyross** [scrapinghub/portia#272]
Admit unnecessary `%25` in http://zakupki.gov.ru/epz/order/quicksearch/search.html?searchString=%25D0%25BA%25D0%25B0%25D1%2582%25D1%2580%25D0%25B8%25D0%25B4%25D0%25B6&morphology=on

when original url was http://zakupki.gov.ru/epz/order/quicksearch/search.html?searchString=катридж&morphology=on

**Comment by Youwotma** [comment]
Should be fixed now, feel free to reopen if you still have this problem
