### ISSUE TITLE
Support for <script> elements

### ISSUE THREAD

**Issue by rdowinton** [scrapinghub/portia#284]
Right now, Portia strips the content within `script` elements to prevent XSS attacks. It would be useful if there was a way to tweak or disable this so it's possible to extract data stored within `script` blocks.

**Comment by Youwotma** [comment]
Hi,

What's your use case? Annotating the whole script or part of the source?

Enabling this would be trivial, but I'm concerned that showing the whole script source in the "No CSS" view would clutter it too much.
