### ISSUE TITLE
Running Portia with Vagrant 

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#286]
Hi 
Is it working in windows or ubuntu?
after run the "vagrant up" command where and how build the portia?

**Comment by ruairif** [comment]
It should work in both. It builds portia automatically

**Comment by agramesh** [comment]
Using vagrant portia is built, and javascript urls loading in portia UI. 
How can crawl data from javascript urls? Can you explain when can enable the javascript in UI?

Thanks.

**Comment by agramesh** [comment]
when i built spider and deployed it in scrapyd 
using command 
 - python C:\Python27\Scripts\scrapyd-deploy scrapyd -p <projectname>
 -  curl http://localhost:6800/schedule.json -d project=<projectname> -d spider=<spidername>

 its shows error like this
![scrapyjs](https://cloud.githubusercontent.com/assets/11834931/10039347/a3998a24-61ee-11e5-9306-59e7ca7311c9.jpg)

is this error depends on scrappjs..

**Comment by agramesh** [comment]
Javascript urls loading through portia UI.
