### ISSUE TITLE
Double encoding of '%' in start url

### ISSUE THREAD

**Issue by mahimams** [scrapinghub/portia#296]
I am having a similar issue as #272  with double encoding of the '%' sign. 
My start url is https://github.com/search?q=stars%3A>500&type=Repositories but it is getting encoded into https://github.com/search?q=stars%253A%253E500&type=Repositories . 
When rendering this double encoded url, the search results page say "We couldn’t find any repositories matching 'stars%3A%3E500' ".

**Comment by Youwotma** [comment]
Hi,

Are you using portia development or master branch?

This should have been addressed here: https://github.com/scrapinghub/portia/commit/733e7c7448c7b2a87462be88463fc71bd34a2833 but It's not on master branch or hosted portia yet.

**Comment by mahimams** [comment]
Hi,
I was using the one hosted on https://portia.scrapinghub.com. 
I'll try using the development branch thanks!

**Comment by mahimams** [comment]
Hello,
I'm trying to test out this encoding issue on the "develop" branch. I'm getting the following error:
u'https://github.com/search?q=stars%3A>500&type=Repositories' is not a u'url'.

<img width="1013" alt="screen shot 2015-10-21 at 1 12 35 pm" src="https://cloud.githubusercontent.com/assets/11027078/10648855/dabf403a-77f5-11e5-8902-a7d747afcfd6.png">
