### ISSUE TITLE
Default field settings

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#300]
Hi can i fix default fieldnames by drop down list in new portia java script branch

**Comment by ruairif** [comment]
Which branch are you currently using? Would you be able to describe the problem in more detail and maybe include some images?

**Comment by agramesh** [comment]
Currently i am using javascript annotation portia UI. Javascript urls loading well, is it possible to add default fields in this location

![dea](https://cloud.githubusercontent.com/assets/11834931/10487609/652a31ec-72b2-11e5-88dc-2c545dde6c7a.jpg)

like this

![capture](https://cloud.githubusercontent.com/assets/11834931/10487627/75730664-72b2-11e5-901a-89ea03460f52.PNG)

**Comment by ruairif** [comment]
I don't understand the use case for adding it.
You can use predefined item schemas when annotating samples and then reuse them later.
You can also copy items between different projects. You can copy spiders, and items to different projects on the page that lists all spiders for a project.
![copy](https://cloud.githubusercontent.com/assets/6472969/10490841/2964fc6c-729b-11e5-86f9-376bd691e5bb.png)

Read more about item schemas here:
http://portia.readthedocs.org/en/latest/items.html
