### ISSUE TITLE
Enable install without an Ubuntu 12.04 wedge

### ISSUE THREAD

**Issue by phil2hood** [scrapinghub/portia#306]
The docker and Vagrant approaches both use a small VM running Ubuntu 12.04, alternatively this works nicely on Ubuntu 12.04.  No offense to that distro, but it is aging.  It would be nice to have the option to put this on a more recent distribution.  Is there a barrier here?

**Comment by ruairif** [comment]
Hi @phil2hood,
The only barrier we have to upgrading from 12.04 is that it is not a priority. It works and 12.04 is still 2 years away from its EOL. If you want to upgrade the Vagrant and Docker scripts for 14.04 feel free to submit a PR. If it works we will happily merge the changes.
