### ISSUE TITLE
docker container is extremely outdated

### ISSUE THREAD

**Issue by Arffeh** [scrapinghub/portia#310]
Hi!

I was wondering if you guys could update https://hub.docker.com/r/scrapinghub/portia/ ?

I plan on writing out a coreOS Unit File, but am experiencing issues with such an old container for issues that I know were fixed earlier this year. :/

Mass deploying over coreOS would be pretty dreamy.

**Comment by ruairif** [comment]
Deploys automatically pushed with each commit to master. Tagged releases will also be available from now on

**Comment by Arffeh** [comment]
Hnnnng thank you so much

**Comment by ruairif** [comment]
Sorry it took so long
