### ISSUE TITLE
Javascript pattern

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#312]
Hi
In javascript url, if patterns given like this for page navigation means
javascript:void()
how can we work in this

**Comment by agramesh** [comment]
+1

**Comment by agramesh** [comment]
Hi 
how could we give patterns for next page urls if it is in javascript. it is highlighted in red box

![nextpageimage](https://cloud.githubusercontent.com/assets/11834931/11807024/fd67d1c0-a33c-11e5-9494-ee411ee674aa.png)

**Comment by ruairif** [comment]
This would need to be done with page actions. Support will be added later this year
