### ISSUE TITLE
ImportError: cannot import name phymem_usage

### ISSUE THREAD

**Issue by siddhant-mohan** [scrapinghub/portia#321]
on running bin/slyd following error occurs
Traceback (most recent call last):
  File "bin/slyd", line 3, in <module>
    import splash.server
  File "/home/ubuntu/production/local/lib/python2.7/site-packages/splash/server.py", line 9, in <module>
    from psutil import phymem_usage
ImportError: cannot import name phymem_usage

**Comment by ruairif** [comment]
Hi. What version of psutil do you have?
The call to `phymem_usage` has been removed from psutil 3.0.0. If you downgrade to psutil 2.2.0 if should work

**Comment by siddhant-mohan** [comment]
Hey,
downgraded to psutil 2.2.0. but still the error is same.

**Comment by ruairif** [comment]
Are you sure that you downgraded psutil in the same environment that you are running Portia in?

**Comment by vgvassilev** [comment]
Seems a flavor of #331. Please see the remedy there ;)
