### ISSUE TITLE
[WebSocket error] Portia cannot connect to the server on OSX.

### ISSUE THREAD

**Issue by ddofborg** [scrapinghub/portia#322]
Portia cannot connect to the server on OSX. WebSocket error.

![20151208-100600](https://cloud.githubusercontent.com/assets/150388/11651749/5a7abeea-9d93-11e5-9f8b-7e853a4c81aa.png)

**Comment by noreff** [comment]
Websocket closed, the same Win 7 via vagrant

**Comment by ccvieira** [comment]
Exactly same problem here,
tried in ubuntu 15.10 via vagrant and via docker, using both firefox and chrome.

**Comment by ccvieira** [comment]
did any of you managed to overcome this error?

**Comment by ddofborg** [comment]
Nope :( Is there any dev which can reply?

**Comment by ruairif** [comment]
Have you tried with the latest version in the master branch?

**Comment by atmosx** [comment]
Hello @ddofborg @ccvieira 

Just tested latest version and works for me. I am using MacOSX 10.11.12

**Comment by ddofborg** [comment]
I just pulled the lastest version. It seems to work. I can create a project now. I will test it further.
