### ISSUE TITLE
ERR_EMPTY_RESPONSE when running portia with Vagrant

### ISSUE THREAD

**Issue by nycreep** [scrapinghub/portia#327]
so after I run vagrant up I go to my browser and then 
i get a black page that says " No data received

ERR_EMPTY_RESPONSE" 

what am I doing wrong guys??

**Comment by Youwotma** [comment]
Hi, the build of splash docker/vagrant images in the master/develop branches is a bit broken, could you try the `qt5` branch instead?

**Comment by vgvassilev** [comment]
Seems a flavor of #331. Please see the remedy there ;)
