### ISSUE TITLE
Vagrant osx ImportError: No module named splash.server

### ISSUE THREAD

**Issue by vgvassilev** [scrapinghub/portia#331]
Following the installation guide http://portia.readthedocs.org/en/latest/installation.html I cannot access localhost:8000. /var/log/upstart/slyd.log says:
```
Traceback (most recent call last):
  File "bin/slyd", line 3, in <module>
    import splash.server
ImportError: No module named splash.server
```

**Comment by Youwotma** [comment]
Hi, the build of splash docker/vagrant images in the master/develop branches is a bit broken, could you try the qt5 branch instead?

**Comment by vgvassilev** [comment]
Thanks for the reply. I don't see a branch qt5, where should I look for it?

**Comment by Youwotma** [comment]
Err, sorry, qt5 branch is only in my fork for the moment

**Comment by vgvassilev** [comment]
Yes, I figured out this was a PR. 
```
git fetch origin pull/330/head:pr-330
git checkout pr-330
```
does the trick. However I still cannot run slyd with the same reason. I tried localhost:8000 and localhost:9001 (since you changed that in the PR). I ran vagrant destroy and vagrant up and I am waiting to see if it would work.

**Comment by vgvassilev** [comment]
Finally it seems to work with one caveat:
PYTHONPATH=/vagrant/slyd:/vagrant/slybot bin/slyd -p 9002 --root ./dist had to be changed to 9001 because this is the port which we forward.
Thanks a lot for the help.
