### ISSUE TITLE
Error in Page Action record option 

### ISSUE THREAD

**Issue by sornalingam** [scrapinghub/portia#339]
Hi All, 

I have pulled the latest version and tried to create sample spider for `timberlandonline.co.uk` . 

When I click the record button I received an Error 
`Unexpected error`

Also I am not sure how to add the next page crawl options. 

Can anyone please help me and what went wrong in the page action option?

Thanks, 
![error](https://cloud.githubusercontent.com/assets/2902053/12326684/4b5e56d8-baf8-11e5-87b2-34632b497d85.png)

**Comment by agramesh** [comment]
+1

**Comment by AlexTan-b-z** [comment]
+1

**Comment by ruairif** [comment]
Page actions feature removed from Portia 2.0 will be readded at a later date
