### ISSUE TITLE
Allow to copy spiders between projects

### ISSUE THREAD

**Issue by kalessin** [scrapinghub/portia#34]

**Comment by ruairif** [comment]
Added:
https://github.com/scrapinghub/portia/commit/6011a6a394cffb756f50a919a0b88a3458c62710
https://github.com/scrapinghub/portia/commit/0d0bba9a2edc5422d31be61e9b19b2c4169117bd
https://github.com/scrapinghub/portia/commit/076d58df5c41aff389c3dc49c13f2260f564b80c
https://github.com/scrapinghub/portia/commit/0c9db103c3a359cd49c906dccf7ee5667a65e126
