### ISSUE TITLE
ImportError: No module named PyQt5.QtCore

### ISSUE THREAD

**Issue by wdfsinap** [scrapinghub/portia#353]
I use ubuntu to install portia but always failed, when i follow your from http://portia.readthedocs.org/en/latest/installation.html following the instructions on Debain. when I run cd slyd
bin/slyd
it shows 
  File "bin/slyd", line 3, in <module>
    import splash.server
  File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 12, in <module>
    from splash.qtutils import init_qt_app
  File "/usr/local/lib/python2.7/dist-packages/splash/qtutils.py", line 11, in <module>
    from PyQt5.QtCore import (QAbstractEventDispatcher, QDateTime, QObject,
ImportError: No module named PyQt5.QtCore

by the way, sudo docker/splash.sh this commands is wrong because there is no splash.sh file under the docker folder

**Comment by Youwotma** [comment]
Hi, that instructions are for portia 15.12, if you want to install the latest version (from master branch) there is updated instructions here: https://github.com/scrapinghub/portia/blob/master/docs/installation.rst#running-portia-locally

**Comment by blacking** [comment]
Not true for me. I follow with ubuntu 14.0.4 this aproach and i get an error:

from PyQt5.QtCore import (QAbstractEventDispatcher, QDateTime, QObject,
RuntimeError: the sip module implements API v11.0 to v11.2 but the PyQt5.QtCore module requires API v11.

I have PyQt5.5.1-gpl a nd sip 4.1.18

with debian wheezy or jessie i received on the first 
 nginx : Depends: libc6 (>= 2.14) but 2.13-38+deb7u10 is to be installed
and on jessie a ppa: secutiry erro!

PLEASE how can make to istall really this project?? 
Thanks
mark
