### ISSUE TITLE
Error in New release

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#359]
Hi 
I am configuring new release in my ubuntu machine, when i load the url it's not loading and display error as internal error like this 
![error portia](https://cloud.githubusercontent.com/assets/11834931/12675921/d8b0d3c8-c6b3-11e5-900b-99a0197bc98e.png)

**Comment by Youwotma** [comment]
We changed some internals and there are some incompatibilities with previous versions of portia. You will need to update/rebuild the docker image.
