### ISSUE TITLE
Multiple Fields

### ISSUE THREAD

**Issue by Gwai2Lo2** [scrapinghub/portia#368]
Hi all,

I need to extract more then one field out of a single annotation. All of them must be based on the attribute content. In the past it seems that there was an add field button, which might would provide the solution I'm looking for but in the current version I can't find this button anymore.

![portia-create-annotation](https://cloud.githubusercontent.com/assets/17036082/12873681/cc81b840-cdfe-11e5-9a23-45f33ea0a35d.png)

The documentation says the following but I have no clue where I can find the Attribute mappings.
> Multiple fields
It’s possible to extract multiple fields using a single annotation if there are several properties you want to extract from an element. For example, if there was an anchor link on the page, you could map the href attribute containing the URL to one field, and you could map the text to another. You can view a particular annotation’s settings by either clicking the cog in the annotation pop-up window or by clicking the cog beside the annotation in the Annotations section of the sample configuration. Within this context there is an Attribute mappings section where you can define additional mappings for the selected annotation should you want to map other attributes.

**Comment by Gwai2Lo2** [comment]
Alright, I figured it out by myself. To extract multiple items from a single annotation is only possible by extracting one as content and the other one as href, to extract two fields as content is not possible.

Is this not possible as it might would slow down the scraping process?

The other possibility would be to extract multiple items from a single annotation with the help of assigning multiple extractors using RegEx but therefore there multiple fields would be required as well which is not possible at the moment.

Only solution for now seems to be to extract multiple items from a single annotation in the post process of the data outside of portia.

**Comment by ruairif** [comment]
Unfortunately you can't currently map a single field within an annotation to many fields. You don't necessarily need to post process the data either. If you know how to write a little bit of Python code you can write what is called a [pipeline](http://doc.scrapy.org/en/latest/topics/item-pipeline.html). Using this you can process the items as they are extracted.

```python
# pipelines.py
class SplitFieldsPipeline(object):
    def process_item(self, item, spider):
        if 'ingredients' in item:
            item['ingredient_1'], item['ingredient_2'] = item['ingredients'].split('and')
        return item
```
You can add this to your project's `settings.py` file like this:
```python
ITEM_PIPELINES = {
    'project.pipelines.SplitFieldsPipeline': 100,
}
```

**Comment by Gwai2Lo2** [comment]
Thanks for the answer, I'll look into this and close the topic.
