### ISSUE TITLE
Support annotation of multiple items per page

### ISSUE THREAD

**Issue by kalessin** [scrapinghub/portia#37]
This first has to be issued at slybot side, then to UI. Idea is to avoid to use variant annotation/split for this

**Comment by icai** [comment]
+1

**Comment by ruairif** [comment]
Hi @icai would you mind explaining your use case for this? Do you want to extract multiples of the same type of item from the same page or do you want to extract multiple different types of items from the same page or both?

**Comment by geoffwalmsley** [comment]
Not @icai but I'm looking to extract multiples of the same type of item from the same page...

**Comment by index01d** [comment]
+1

**Comment by andrei512** [comment]
+1

**Comment by jimmykhlam** [comment]
+1

**Comment by charlienewey** [comment]
+1

**Comment by ruairif** [comment]
Available in Portia 2.0

**Comment by matsutakako** [comment]
I try to scrape some multiple items from a single page, but it doesn't work, any ideas?
