### ISSUE TITLE
xpath support to portia

### ISSUE THREAD

**Issue by drprabhakar** [scrapinghub/portia#375]
Is it possible to use xpath instead of data-tagid for annotated fields?
This will prevent content mismatch if any field is missing.
Ex: Page-1
         <div> text1
         <div> text2
         <div> text3
      Page-2
         <div> text1
         <div> text3
Scenario:
     Annotated all the text and mapped to individual fields from Page 1(Field1=text1, Field2=text2, so on). While running spider, we get each text will be mapped to respective fields for Page-1. But for Page-2, the fields would be mapped like((Field1=text1, Field2=text3) and this will give wrong data for Filed-2.

To avoid this, it will be better if we have xpath support in portia.

**Comment by ruairif** [comment]
Portia doesn't use XPath to decide what data to extract but instead uses the [scrapely](https://github.com/scrapy/scrapely) library. This works by using sample pages to guide the extraction of data from an unknown page. While you see `data-tagid` in the UI this is only used as a way to provide a unique id to each element so annotations can be added to the sample page correctly and is not used when extracting data. We will be releasing a feature in the coming weeks that will allow you to export your spider as a standard scrapy spider that uses XPath and CSS selectors to extract data and hopefully that will solve the problem you are having.
