### ISSUE TITLE
portia-portia-16.02.2_Error in Run time

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#376]
Hi I am configuring portia new release "portia-portia-16.02.2" in ubuntu 12.04 LTS OS. The before release "portia-15.12.2" working fine for me. but in new release when i run the command "bin/slyd"
i receive error like this 

Traceback (most recent call last):
  File "bin/slyd", line 29, in <module>
    splash.server.main(server_factory=make_server, argv=[])
TypeError: main() takes no arguments (2 given)

how can i clear it. 
thanks in advance.

**Comment by ruairif** [comment]
You will need to run the install steps again. Your version of splash is out of date.

**Comment by agramesh** [comment]
already the installed splash version is 1.8 
now the portia UI loading in browser, but when I load the url in UI error received as "internal server error" 
![errorportia](https://cloud.githubusercontent.com/assets/11834931/13176058/1bed0bd4-d735-11e5-8c5b-71fd061a3891.png)

**Comment by ruairif** [comment]
How did you install portia?

**Comment by agramesh** [comment]
cd ~portia/portia
pip install --upgrade pip
pip install -r slybot/requirements.txt
pip install -r slyd/requirements.txt
pip install pyopenssl ndg-httpsclient pyasn1
pip install splash
pip install scrapy
pip install jsonschema
pip install scrapely
pip install rfc3987
pip install loginform
pip install autobahn
pip install monotonic
pip install chardet
pip install requests
pip install scrapyjs
pip install dateparser
pip install -e slybot
pip install -e slyd

**Comment by ruairif** [comment]
By installing splash that way you install an older version of it. We are currently using splash-2.0 in Portia, (it is scheduled for release next week). To install splash-2.0 run
`pip install  git+https://github.com/scrapinghub/splash`

**Comment by agramesh** [comment]
while installing splash-2.0 using the above command 
 error: The requested URL returned error: 403 while accessing http://github.com/scrapinghub/splash-2.0/info/refs
  fatal: HTTP request failed

**Comment by ruairif** [comment]
Did you run the command I added above?

**Comment by agramesh** [comment]
yes i run the above command, it shows error as

error: The requested URL returned error: 403 while accessing http://github.com/scrapinghub/splash-2.0/info/refs
fatal: HTTP request failed

**Comment by ruairif** [comment]
The request failed because the repository `https://github.com/scrapinghub/splash-2.0` doesn't exist. Are you adding a `-2.0` to the end of the pip install command?

**Comment by agramesh** [comment]
yes i tried like this its installed splash 2.0. and  to run the splash is it required pyqt5, because error comes

  File "/usr/local/bin/splash", line 3, in <module>
    from splash.server import main
  File "/usr/local/lib/python2.7/dist-packages/splash/server.py", line 12, in <module>
    from splash.qtutils import init_qt_app
  File "/usr/local/lib/python2.7/dist-packages/splash/qtutils.py", line 11, in <module>
    from PyQt5.QtCore import (QAbstractEventDispatcher, QDateTime, QObject,
ImportError: No module named PyQt5.QtCore


shall i install pyqt5 to run the splash. is it work?

**Comment by ruairif** [comment]
Yes you need to install pyqt5

**Comment by agramesh** [comment]
is this portia required python3 or else can run in python2.7.6?
