### ISSUE TITLE
Installation doc out of date

### ISSUE THREAD

**Issue by flip111** [scrapinghub/portia#377]
https://portia.readthedocs.org/en/latest/installation.html#debian

Here it says to run this command `sudo docker/splash.sh`

There is 2 issues with this. If you follow the installation instructions by the letter, then first you must do `cd portia` (with only comes later in the installation instructions). And second `splash.sh` is not available, only `compile-assets.sh` and `restore-mtime.sh`

**Comment by Youwotma** [comment]
Hi, the instructions should be updated now, please check again.
