### ISSUE TITLE
Vagrant variant still broken?

### ISSUE THREAD

**Issue by TimoC1982** [scrapinghub/portia#382]
Hey guys,

Is the vagrant variant still broken?
I installed portia on Windows last year and used it, and take an upgrade in january (Notebook Change) since them the vagrant Version is broken. If i try to open the webinterface on port 9001 it still get an error. I Changed the ports in the slyd konfig and redeployed the enviroment with the same error.
Any hints?

Regards Timo

**Comment by ruairif** [comment]
Have you tried building with the latest version?

**Comment by TimoC1982** [comment]
Hi rairif,
I tried the latest Master Version 16.02.2

regards
Timo

**Comment by TimoC1982** [comment]
Problem fixed. Reinstalled the entire virtual machine and the Image. After them the Version works.
