### ISSUE TITLE
Portiacrawl: SPIDER_MANAGER_CLASS option is deprecated

### ISSUE THREAD

**Issue by TimoC1982** [scrapinghub/portia#391]
Hi Guys,
If i try to start an Spider in the new Version i get following error:

vagrant@portia:/vagrant/slyd/slyd/data/projects$ portiacrawl /vagrant/slyd/slyd/data/projects/new_project -v
scrapy list -s PROJECT_DIR=/vagrant/slyd/slyd/data/projects/new_project -s SPIDER_MANAGER_CLASS=slybot.spidermanager.SlybotSpiderManager
/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py:115: ScrapyDeprecationWarning: SPIDER_MANAGER_CLASS option is deprecated. Please use SPIDER_LOADER_CLASS.
  self.spider_loader = _get_spider_loader(settings)

Any hints?

Regards
Timo

**Comment by ruairif** [comment]
It is just a Deprecation Warning it is not a problem for now but this will need to be updated before support is dropped from scrapy
