### ISSUE TITLE
repository doesn't have package for willy

### ISSUE THREAD

**Issue by flip111** [scrapinghub/portia#428]
when i do `sudo apt-get update` all is fine.

Now i run `sudo ./provision.sh install_splash install_python_deps` and get:

```
W: Failed to fetch http://ppa.launchpad.net/beineri/opt-qt551-trusty/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found
```

Now when doing `sudo apt-get update` again i keep getting this error, so i guess portia adds repositories to my system? How can i run portia? My system is ubuntu 15.10

**Comment by luigilabel** [comment]
+1 nor 16.4 neither 15.10 have this ppa working correctly. Can anyone explain a step by step solution??
