### ISSUE TITLE
Error running on Docker 

### ISSUE THREAD

**Issue by vicgrad** [scrapinghub/portia#453]
Hey, I followed the installation quide, got the docker running, opened index.html, but when I enter a domain url to start a project I get the following error and docker stops:

> process 13: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
> See the manual page for dbus-uuidgen to correct this issue.
> Traceback (most recent call last):
>   File "/app/slyd/slyd/splash/ferry.py", line 144, in wrapUrl
>     return wrap_url(text(url), self.protocol.user.tabid, text(baseuri))
>   File "/app/slyd/slyd/splash/css_utils.py", line 17, in wrap_url
>     url = urljoin_rfc(base, url)
>   File "/usr/local/lib/python2.7/dist-packages/w3lib/url.py", line 60, in urljoin_rfc
>     str_base = unicode_to_str(base, encoding)
> NameError: global name 'unicode_to_str' is not defined
> Aborted

Any idea how to work around this?

**Comment by devNo0b** [comment]
hi @vicgrad as you can see here, the latest version of this library actually breaks stuff
https://github.com/scrapy/w3lib/issues/51
For now, just clearly state the library version in the requirements, then you will be fine

So, all you have to do is open file /slyd/requirements.txt , put this line **w3lib==1.13.0** in, then build again and you are good to go

**Comment by redapple** [comment]
new w3lib v1.14.2 is out.
@vicgrad , can you check if the issue is solved with this new release?

**Comment by vicgrad** [comment]
Hi,

@devNo0b Thanks for the tip, I managed to move past the error and to load a page. After trying to annotate the page though, the docker image failed again. 

The error reads:

> Traceback (most recent call last):
>   File "/app/slyd/slyd/splash/ferry.py", line 165, in sendMessage
>     self.protocol.sendMessage(metadata(self.protocol))
>   File "/app/slyd/slyd/splash/commands.py", line 83, in metadata
>     socket.tab.loaded = True
> AttributeError: 'NoneType' object has no attribute 'loaded'
> Aborted
> 

@redapple Tried v1.14.2 and it behaves similar to v1.13.0

When I build the docker image it shows the following in the logs:

> ...
> Downloading/unpacking w3lib==1.14.2 (from -r /app/slyd/requirements.txt (line 1))
>   Downloading w3lib-1.14.2-py2.py3-none-any.whl
> ...
> Requirement already satisfied (use --upgrade to upgrade): w3lib>=1.8.0 in /usr/local/lib/python2.7/dist-packages (from scrapy==1.0.0->-r /app/slybot/requirements.txt (line 2))
> ...

**Comment by devNo0b** [comment]
@redapple I got that error exactly the same to you. Not sure why also. Sometimes, it can be this error too, when we annotate the page.
[(https://github.com/scrapinghub/portia/issues/438)]
Still no respond
