### ISSUE TITLE
Portiacrawl command issue

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#462]
Hi 
I run the portia crawl command to deploy the spider, but show error like this

command : 
 docker run /app/slybot/bin/portiacrawl <projectpath> <spidername> 
error : 
 docker: Error parsing reference: "/app/slybot/bin/portiacrawl" is not a valid repository/tag.

what is the issue in this

**Comment by agramesh** [comment]
hi
any update

**Comment by Spaghet** [comment]
uhhhhh 

`docker run <INSERT_PORTIA_DOCKER IMAGE HERE> /app/slybot/bin/portiacrawl`

should do it, check out some docker tutorials https://docs.docker.com/engine/getstarted/
