### ISSUE TITLE
How to install Portia 2.0 beta

### ISSUE THREAD

**Issue by majkelos01** [scrapinghub/portia#487]
Hi guys, 
I'm loving new beta that's available via scraping hub. 
Is there any chance to download it on my own machine?

Cheers

**Comment by ruairif** [comment]
Hi @majkelos01 
You can use the new version of portia by checking out the nui-develop branch
If you have any problems setting it up please post them here and we can help you get it set up

**Comment by majkelos01** [comment]
@ruairif 
Thank you for that 
Have  a good one!
