### ISSUE TITLE
Docker build failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by trungdq88** [scrapinghub/portia#504]
I'm trying to run `docker build -t portia .` on my Ubuntu 14.04 and get this error:

```
{standard input}: Assembler messages:
{standard input}:305494: Warning: end of file not at end of a line; newline inserted 
{standard input}: Error: .size expression for _ZNK11sipQLibrary10metaObjectEv does not evaluate to a constant g++: internal compiler error:
Killed (program cc1plus) Please submit a full bug report, with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions. make[1]: *** [sipQtCorepart0.o]
Error 4 make[1]: Leaving directory `/builds/PyQt-gpl-5.5.1/QtCore' make: *** [sub-QtCore-make_first-ordered]
Error 2
```

It works fine on my OSX but failed on my Digital Ocean Ubuntu 14.04, is this a known bug?

**Comment by agramesh** [comment]
+1

**Comment by makelove** [comment]
Get:25 http://archive.ubuntu.com trusty/universe amd64 Packages [17.0 kB]
Fetched 25.4 MB in 25s (988 kB/s)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/restricted/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/restricted/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/restricted/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/universe/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/universe/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/restricted/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/universe/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c /app/provision.sh         install_deps         install_splash         install_python_deps         configure_nginx         cleanup' returned a non-zero code: 100


Fail too
