### ISSUE TITLE
Error in css_utils.ph

### ISSUE THREAD

**Issue by lonnietc** [scrapinghub/portia#512]
Greetings All,

I have only recently found Portia and tried to install it on my Ubuntu 15.04 system in a docker environment but ran into a problem.

From what I could find, there is an error in the css_utils.py 

portia/slyd/slyd/splash/css_utils.py

in that file, there are 2 exact statements at line 18 & 19

17        # character reference
18       if entity[:3] == "&#x":
19        if entity[:3] == "&#x":
.
.
.

I have to comment out line 18 to get Portia to run.

Can this be fixed in the github repository so that we do not have to manually edit the file?

Thanks,
Lonnie

**Comment by ruairif** [comment]
Thank you for pointing this out. I have now released a fix

**Comment by lonnietc** [comment]
Hello,

Not sure if this is critical, but I am now able to start up the docker image with no problems:

--------------------------------------------
lonnie@ost1:~/portia$ docker run -i -t --rm -v /home/lonnie/data:/app/slyd/data:rw -p 9001:9001 portia
2016-06-16 14:42:54+0000 [-] Log opened.
2016-06-16 14:42:54.351849 [-] Splash version: 2.1
2016-06-16 14:42:54.353182 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
2016-06-16 14:42:54.353260 [-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 15.4.0
2016-06-16 14:42:54.354496 [-] Python 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
2016-06-16 14:42:54.354680 [-] Open files limit: 1048576
2016-06-16 14:42:54.354815 [-] Can't bump open files limit
2016-06-16 14:42:54.513331 [-] Xvfb is started: ['Xvfb', ':1', '-screen', '0', '1024x768x24']
--------------------------------------------

but, I was wondering about the:

"2016-06-16 14:42:54.353182 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed"

and wanted to know if this was something that should be installing with the setup dependencies?

Cheers
Lonnie

**Comment by ruairif** [comment]
Everything should work fine without it

**Comment by lonnietc** [comment]
Thanks again as I was just curious about that warning and if it had any
impact.

Next I would like to learn how to use Portia and will be reviewing your
documentation and videos after which I will be look at your other github
repositories for commandline running these spiders on a Ubuntu 14.04 system
that I have set up because Ubuntu 15.04 is not supported for Portia outside
of a docker container. Maybe that will come soon, but I could not get
everything to compile up properly due to some missing PPA location files.

Thanks again for a great product.

Cheers,
Lonnie
