### ISSUE TITLE
Testing Portia

### ISSUE THREAD

**Issue by lonnietc** [scrapinghub/portia#513]
Greetings,

I was recently testing out Portia on a site and it came back with a message that "Frames are not supported by Portia"

I was wondering if there are plans to support frames as a number of sites seem to have this built in?

Thanks,
Lonnie

**Comment by drprabhakar** [comment]
Refer: [frame and iframe support in Portia|https://github.com/scrapinghub/portia/issues/494#issuecomment-224198652]

**Comment by agramesh** [comment]
+1

**Comment by TheFonz2017** [comment]
+1
