### ISSUE TITLE
`portiacrawl` and Javascript

### ISSUE THREAD

**Issue by charlienewey** [scrapinghub/portia#518]
I am using the Vagrant environment provided in the git repo, and have been trying to use Portia to create a scraper that can execute JS. JS appears to work in the "annotate" environment within the Portia web app, but when running the resultant scraper with "portiacrawl" (e.g. `portiacrawl /vagrant/slyd/slyd/data/Project crawlername`), there is no output and it seems that the JS is not getting executed. The scraper functions as intended under the `annotate` environment - so is there a way to get JS working under portiacrawl? It's probably something stupid that I have missed.

**Comment by agramesh** [comment]
+1

**Comment by ruairif** [comment]
You need to configure a [splash](http://splash.readthedocs.io/en/stable/install.html) container and add a `SPLASH_URL` to your project settings

**Comment by matthieu637** [comment]
The addition of SPLASH_URL worked for me. 
However, if I perform a login on a site, it doesn't work. Do I have to configure splash to perform a login? (I've already filled up the "Initialization - Perform login" part).
