### ISSUE TITLE
 "docker run -i -t --rm -v <PROJECT_FOLDER>/data:/app/slyd/data:rw -p 9001:9001 --name portia portia" 

### ISSUE THREAD

**Issue by YanchaoJia** [scrapinghub/portia#529]
执行 docker run -i -t --rm -v <PROJECT_FOLDER>/data:/app/slyd/data:rw -p 9001:9001 --name portia portia
"-bash: PROJECT_FOLDER: 没有那个文件或目录 " 怎么解决的 这个 PROJECT_FOLDER 怎么解决??

**Comment by agramesh** [comment]
hi YanchaoJia
if you are working in linux means use the below command, it will work
   - sudo docker run -i --rm -v /home/data/projects:/app/slyd/slyd/data:rw -p 9001:9001 --name portia portia

or using windows means  use
- docker run -i --rm -v /c:/data/projects:/app/slyd/slyd/data:rw -p 9001:9001 --name portia portia

**Comment by YanchaoJia** [comment]
Haha Thank you so much . A lot of people are directly handling the document , it is very difficult to understand for people who have no contact docker , I saw your example , I immediately understand what it means , this is my Google Translation the (∩_∩)

**Comment by sjguan** [comment]
@agramesh 
"/home/data/projects:/app/slyd/slyd/data:rw"
my system is vm of ubuntu,'home' folder below not found ‘data‘.
what's <PROJECT_FOLDER> mean?

**Comment by drprabhakar** [comment]
@WuliShijie 
The <PROJECT_FOLDER> is the local path where you want to save your portia spiders.
