### ISSUE TITLE
Page Navigation

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#533]
Hi 
I tried the pageaction in portia to scrape multi page data. But its not working. While click the pageaction i recieved internal error in portia. And also while i deployed the spider in scrapyd first page data only scraped. Is there any otherway to scrape the multipage data. Or how can i add a middleware for the pageaction. I have tried a scrapy selenium script for the url. Is it possible to add the selenium script as a middleware with portia. I tried but not working. Can anyone help me to create a middleware or tell the way to scrape multipage data please.

**Comment by ruairif** [comment]
You can create a middleware to run your selenium script. Just add it to your settings file and make sure that the `scrapy.cfg` points to the correct settings file
