### ISSUE TITLE
Portia can't perform if adding javascript to manipulate html

### ISSUE THREAD

**Issue by dongchirua** [scrapinghub/portia#538]
I would like to manipulate html so that I added a javascript file (say `run.js`) to `splash_utils` folder. I also made changes on `splash_utils/compile_slybot.sh` as well as `slyd/index.js` to generate a new file `combined.js` at `slyd/dist/splash_content_scripts`

My file is like 

```
var f = function () {
  var body = document.body;
  var placeholderElems = body.querySelectorAll('.delayed-image-load');
  // I had included at treeForPublic  (`slyd/index.js`) to load Imager.js library.
  var imgrPlaceholder = new Imager(placeholderElems, {availableWidths: [320]});
};
f();
```

Problem is when I load a heave page like www.bbc.com, Portia can't load website at all. I said a heave page because I had made an example which a proportion of bbc.com and Portia could load this. I give this example here [testImage_nojs.html.zip](https://github.com/scrapinghub/portia/files/377855/testImage_nojs.html.zip)

Would you please check if it is a bug or not?

**Comment by ruairif** [comment]
It loads in Portia 2.0
