### ISSUE TITLE
exceptions.AttributeError: 'FerryServerProtocol' object has no attribute 'autoPingPendingCall'

### ISSUE THREAD

**Issue by agramesh** [scrapinghub/portia#543]
hi
while running portia 15.09 version using docker in centos i received error as 

```
      File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1209, in _connectionLost
        if self.autoPingPendingCall:
    exceptions.AttributeError: 'FerryServerProtocol' object has no attribute 'autoPingPendingCall'
```

can you please help me to resolve this

**Comment by ruairif** [comment]
Can you try rebuilding your docker image. It seems like you have a version mismatch

**Comment by agramesh** [comment]
hi 
i configured the new version of portia using docker, running fine but some time it closed automate and shows error as
  File "/app/slyd/slyd/splash/ferry.py", line 165, in sendMessage
    self.protocol.sendMessage(metadata(self.protocol))
  File "/app/slyd/slyd/splash/commands.py", line 83, in metadata
    socket.tab.loaded = True
AttributeError: 'NoneType' object has no attribute 'loaded'
Aborted (core dumped)
