### ISSUE TITLE
Debian VPS Install

### ISSUE THREAD

**Issue by nshake** [scrapinghub/portia#556]
I have tried 7 different tutorials (inculding the portia documentation) and have almost got everything up and running.

I have spent days, weeks and many hours trying to make this work.

I ended up getting this together to work until the last step:

```
#Debian#


#Running Portia Locally#

#These instructions are only valid for a Debian based OS#

#Connect via SSH to your VPS and login as “root”#

#As root:#

apt-get update

apt-get install sudo

useradd -d /home/portia -s /bin/bash -m portia

passwd portia

echo "portia ALL=(ALL:ALL) ALL">> /etc/sudoers.d/portia

chmod 0440 /etc/sudoers.d/portia

exit

#Login with newly created “portia” account and enter password#

#Install virtualenv and git:#

sudo apt-get install virtualenv

sudo apt-get install git

#If you would like to run Portia locally you should create an environment with virtualenv:#

virtualenv crawler --no-site-packages

source crawler/bin/activate

cd crawler

#NOTE: you can name the env anything you'd like. I named it “crawler”,#
#but you can name it anything#

#Now clone this repository into that env:#

git clone https://github.com/scrapinghub/portia.git

#Go into Portia (inside the “crawler” env):#

cd portia

#Install the following dependencies:#

sudo ./provision.sh install_deps

#Install splash and the required packages:#

sudo ./provision.sh install_splash install_python_deps

#To run portia start slyd:#

cd slyd
bin/slyd

#Portia should now be running on port 9001 and you can access it at http://localhost:9001.#
```

I got this pieced together from many different tutorials that didn't work.

Everything seems fine, but when I get to running:

**bin/slyd**

I get errors...

**Here is my full log:**

ATTACHED
[portia-install-log.txt](https://github.com/scrapinghub/portia/files/417634/portia-install-log.txt)

Anything you could do to help would be greatly appreciated.

Thank You, and Thank You for making all this available to everyone!

**Comment by doksec** [comment]
`W: Failed to fetch http://ppa.launchpad.net/pi-rho/security/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found`

ubuntu jessie ? Debian!

**Comment by nshake** [comment]
Debian VPS Install: Jessie
