### ISSUE TITLE
Portia (Vagrant) can`t open page behind a proxy

### ISSUE THREAD

**Issue by dorvak** [scrapinghub/portia#557]
Hi,

 I#m running Portia behind a company proxy using Vagrant (defining theProxy Settings in the Vagrantfile) on Mac OS 10.11.5. While the Portia interface itself starts without any issues (Note: I needed to change the port to 9001 in slyd.conf), I'm not able to open any website within Portia itself. Every requests results in:

> Failed loading page (Socket operation timed out)
> 
> http://www.google.com
> 
> Network error #4 

The logs from slyd say:

> 2016-08-17 17:33:32.339094 [-] "10.0.2.2" - - [17/Aug/2016:17:33:32 +0000] "GET /projects/Scoutia/spec/items HTTP/1.1" 200 48 "http://localhost:9001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
> 2016-08-17 17:33:32.703776 [-] "10.0.2.2" - - [17/Aug/2016:17:33:32 +0000] "GET /assets/ZeroClipboard.swf?noCache=1471455214194 HTTP/1.1" 200 6580 "http://localhost:9001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
> 2016-08-17 17:33:40.476439 [HTTPChannel,11,10.0.2.2] u'Websocket Closed: id=6776-35f6-9e65 t=9.570063482 user=defaultuser command='
> 2016-08-17 17:35:08.205747 [-] "10.0.2.2" - - [17/Aug/2016:17:35:07 +0000] "GET /static/empty-frame.html?a96d-aa88-0d95 HTTP/1.1" 200 194 "http://localhost:9001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17"

Any take on this one?

**Comment by dirtychash** [comment]
you may need to look at port forwarding.
