### ISSUE TITLE
Emberjs slyd? 

### ISSUE THREAD

**Issue by yj36963** [scrapinghub/portia#558]
slyd is an app based on Emberjs? I don't know the relationship of Emberjs and twisted

**Comment by sagelliv** [comment]
`slyd` is responsible for running the Twisted reactor which is the entry point to the resources for the backend (resources like Portia projects). Portia's `master` branch constructs the Emberjs app in the `slyd/dist` directory, and has the entire Emberjs app in `slyd/app`. The new Portia UI has been decoupled from slyd into the `portiaui` directory.
