### ISSUE TITLE
Can portia export scrapy python code

### ISSUE THREAD

**Issue by whenjonny** [scrapinghub/portia#561]
Can i use portia to export scrapy code?

**Comment by sagelliv** [comment]
You can use https://github.com/scrapinghub/portia2code to convert a Portia spider into a scrapy.

**Comment by ruairif** [comment]
@whenjonny You can find more info [here](https://blog.scrapinghub.com/2016/06/29/introducing-portia2code-portia-projects-into-scrapy-spiders/)
