### ISSUE TITLE
What does the directory slyd/splash_utils do?

### ISSUE THREAD

**Issue by netpaladinx** [scrapinghub/portia#566]
I know that portia uses splash to render the webpage, right? But what's the specific role of the directory _slyd/splash_utils_? How does it work with other parts of portia?

**Comment by ruairif** [comment]
The files in the splash_utils directory are used to inject javascript into each page that is loaded so we can interact with them. The javascript that it injects allows us to run actions on the page (if you click something in your browser then that event is sent to splash to run on the page) and it also allows page changes to be sent from the server to your browser using [mutation observer](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver).
