### ISSUE TITLE
how does portia deal with high concurrency?

### ISSUE THREAD

**Issue by Bruce-Dong** [scrapinghub/portia#569]
I meet with a trouble frequently as follow;
when i launch the portia server  and visit the web app locally, it's okay and there is only one connection, but sometimes it starts showing "can't connect to..."and "Internal Server Error" when another connection comes. Is it the problem of some concurrent issue? 
Look forward to seeing some help.

**Comment by ruairif** [comment]
Hi @Bruce-Dong are you running Portia on your own system or are you using portia.scrapinghub.com?

**Comment by Bruce-Dong** [comment]
hi @ruairif  on my own system , centos7.0

**Comment by ruairif** [comment]
On your own system you will need to run multiple instances of portia and place a load balancer in front of them. When you get errors what is logged to the console?
