### ISSUE TITLE
how to configure the database for portia

### ISSUE THREAD

**Issue by Bruce-Dong** [scrapinghub/portia#570]
i have to say that portia is a very nice product ,and i have used many times,
there i suffer from a issues,i can't find the extracted data,there somethind wrong with my database? and how to configure the database for portia is appropriate?

**Comment by ruairif** [comment]
When you run `portiacrawl` you need to use a `-o` argument to save the extracted data.
For example:
`portiacrawl my_project example.com -o items.jl`
This will output all extracted items to a file called `items.jl` and there will be one json object on each line of the file.

**Comment by Bruce-Dong** [comment]
yeh i see ,and i'd like to contribute to portia ,can i have your contact way. like facebook or anything else?
