### ISSUE TITLE
Is the dashboard open source, which we can monitor the process of running portia-generated code？

### ISSUE THREAD

**Issue by juesexiangyang** [scrapinghub/portia#571]
When I was running  the portia-generated code on scrapinghub , there is a dashboard which shows the projects and spiders and can monitor the state of them, so  could I get a dashboard set locally when I run portia on my own environment? Looking forward to any help.

**Comment by ruairif** [comment]
You can try [scrapyd](https://github.com/scrapy/scrapyd) but it is not as full featured as what you get on scrapinghub.com
