### ISSUE TITLE
UI for creating a project in nui-develop

### ISSUE THREAD

**Issue by netpaladinx** [scrapinghub/portia#572]
I set up a portia of nui-develop and launched it successfully on my local machine. However, I cannot find the ui for creating a project. Did I miss something during installation? On the scrapinghub platform, we can access the dashboard to click "Create Project". But lacking a dashboard support, it seems unable to create a project and start the experience of portia 2.0.

**Comment by ruairif** [comment]
We haven't added support for running portia in nui-develop without a MySQL backend yet. When this is available I'll update the docs and ping you here. For now you can sign up for a [Scrapy Cloud](app.scrapinghub.com) account and try Portia 2.0 there
