### ISSUE TITLE
Switching to old UI

### ISSUE THREAD

**Issue by Immortalin** [scrapinghub/portia#574]
Hi, I have been trying to switch to the old UI on scrapinghub in order to use the regex overlay but to no avail. When I clicked on the `Switch to Previous Portia UI` button, the page would refresh but nothing actually happens.

**Comment by ruairif** [comment]
By regex overlay do you mean the link highlighting? If so you can enable this by pressing the :link: icon.

If you need to switch back to the previous UI. You can try clearing your cookies.
