### ISSUE TITLE
how to use proxy for slyd

### ISSUE THREAD

**Issue by dirtychash** [scrapinghub/portia#575]
Hi all
I have been looking for quite a while on how to use a proxy with portia. I can configure slybot to use a proxy for crawling no problem. and have configured scrapyjs and splash middleware to use a proxy also and tested splash stand alone works fine. But i cant seem to find where portia fetches the page. i see QTNetworks but am sure i dont have to configure that. I have launched portia like so:
# slyd --proxy-profiles-path=/vagrant/slyd/slyd/splash/proxy-profiles

vagrant@portia:/vagrant/slyd$ slyd --proxy-profiles-path=/vagrant/slyd/slyd/splash/proxy-profiles
 [-] Log opened.
 [-] Splash version: 1.8
 [-] WARNING: Lua scripting is not available because 'lupa' Python package is not installed
[-] Qt 5.5.1, PyQt 5.5.1, WebKit 538.1, sip 4.17, Twisted 15.4.0
 [-] Python 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
 [-] Open files limit: 1024
[-] Open files limit increased from 1024 to 4096
 [-] Xvfb is started: ['Xvfb', ':1343', '-screen', '0', '1024x768x24']
 [-] proxy profiles support is enabled, 
proxy profiles path: /vagrant/slyd/slyd/splash/proxy-profiles
 slyd.splash.proxy.ProxyResource instance at 0x7fbadf7bbd88
Site starting on 9001
Starting factory slyd.server.Site instance at 0x7fbadf7bbf80

But when i try to view a webpage in portia , it dose not use the proxy.
Please help me with this i have been looking into it for a while.
i have also tried adding middleware to portia/slyd/slyd/settings.py

DOWNLOADER_MIDDLEWARES = {
    'slybot.splash.SlybotJsMiddleware': 725
}

Its probably some thing simple i am missing.
Thanks for any help it would be very much appreciated.

**Comment by ruairif** [comment]
You can set up a proxy on your vagrant box. Supporting proxies within portia isn't possible at the moment
