### ISSUE TITLE
error unexpected error

### ISSUE THREAD

**Issue by jemjov** [scrapinghub/portia#576]
hi all

i dont know why this happen and how to solve this 
i got some error while i click new sample the GUI for enter new sample not happen but  got this error appear

![portia error](https://cloud.githubusercontent.com/assets/14123424/18573298/4f01f38e-7bec-11e6-861c-4b79bb57fdea.jpg)

can anyone help me to solve this?

**Comment by grendy** [comment]
+1

**Comment by dirtychash** [comment]
Try using Developer tools in browser to trace the error back,it some times helps to find where in the error is occurring.

**Comment by jemjov** [comment]
@dirtychash can u tell me which one the developer tools is??

**Comment by j2l** [comment]
I have the same problem.
FF Console replies:
AdapterError: The backend responded with an error
'69de-4db9-9a46'
It is a server internal error, not on client side.

On Chrome, it throws a first error when clicking new spider:
(index):7 GET https://portia-beta.scrapinghub.com/api/projects/101430/spiders/www.amazon.com/samples 500 (Internal Server Error)nrWrapper @ (index):7(anonymous function) @ raven.js:958send @ vendor-8f6b42c….js:5ajax @ vendor-8f6b42c….js:5_ajaxRequest @ vendor-8f6b42c….js:27(anonymous function) @ vendor-8f6b42c….js:27_ @ vendor-8f6b42c….js:19d @ vendor-8f6b42c….js:19ajax @ vendor-8f6b42c….js:27query @ vendor-8f6b42c….js:27d @ vendor-8f6b42c….js:26_query @ vendor-8f6b42c….js:26query @ vendor-8f6b42c….js:26afterModel @ portia-web-588b0fc….js:4p @ vendor-8f6b42c….js:19runSharedModelHook @ vendor-8f6b42c….js:18runAfterModelHook @ vendor-8f6b42c….js:18(anonymous function) @ vendor-8f6b42c….js:19y @ vendor-8f6b42c….js:19b @ vendor-8f6b42c….js:19v @ vendor-8f6b42c….js:19(anonymous function) @ vendor-8f6b42c….js:13invokeWithOnError @ vendor-8f6b42c….js:5flush @ vendor-8f6b42c….js:5flush @ vendor-8f6b42c….js:5end @ vendor-8f6b42c….js:5run @ vendor-8f6b42c….js:5join @ vendor-8f6b42c….js:5u.join @ vendor-8f6b42c….js:11c.success @ vendor-8f6b42c….js:27l @ vendor-8f6b42c….js:4fireWith @ vendor-8f6b42c….js:4n @ vendor-8f6b42c….js:5(anonymous function) @ vendor-8f6b42c….js:5d @ raven.js:329nrWrapper @ (index):7

Then on creating a new data format (new sample button never came), 2 internal errors:
(index):7 GET https://portia-beta.scrapinghub.com/api/projects/101430/schemas/f820-4cc0-90c5/fields 500 (Internal Server Error)nrWrapper @ (index):7(anonymous function) @ raven.js:958send @ vendor-8f6b42c….js:5ajax @ vendor-8f6b42c….js:5_ajaxRequest @ vendor-8f6b42c….js:27(anonymous function) @ vendor-8f6b42c….js:27_ @ vendor-8f6b42c….js:19d @ vendor-8f6b42c….js:19ajax @ vendor-8f6b42c….js:27query @ vendor-8f6b42c….js:27d @ vendor-8f6b42c….js:26_query @ vendor-8f6b42c….js:26query @ vendor-8f6b42c….js:26afterModel @ portia-web-588b0fc….js:4p @ vendor-8f6b42c….js:19runSharedModelHook @ vendor-8f6b42c….js:18runAfterModelHook @ vendor-8f6b42c….js:18(anonymous function) @ vendor-8f6b42c….js:19y @ vendor-8f6b42c….js:19b @ vendor-8f6b42c….js:19v @ vendor-8f6b42c….js:19(anonymous function) @ vendor-8f6b42c….js:13invokeWithOnError @ vendor-8f6b42c….js:5flush @ vendor-8f6b42c….js:5flush @ vendor-8f6b42c….js:5end @ vendor-8f6b42c….js:5run @ vendor-8f6b42c….js:5join @ vendor-8f6b42c….js:5u.join @ vendor-8f6b42c….js:11c.success @ vendor-8f6b42c….js:27l @ vendor-8f6b42c….js:4fireWith @ vendor-8f6b42c….js:4n @ vendor-8f6b42c….js:5(anonymous function) @ vendor-8f6b42c….js:5d @ raven.js:329nrWrapper @ (index):7

(index):7 PATCH https://portia-beta.scrapinghub.com/api/projects/101430/schemas/f820-4cc0-90c5 500 (Internal Server Error)nrWrapper @ (index):7(anonymous function) @ raven.js:958send @ vendor-8f6b42c….js:5ajax @ vendor-8f6b42c….js:5_ajaxRequest @ vendor-8f6b42c….js:27(anonymous function) @ vendor-8f6b42c….js:27_ @ vendor-8f6b42c….js:19d @ vendor-8f6b42c….js:19ajax @ vendor-8f6b42c….js:27updateRecord @ vendor-8f6b42c….js:27updateRecord @ portia-web-588b0fc….js:23r @ vendor-8f6b42c….js:11k @ vendor-8f6b42c….js:26(anonymous function) @ vendor-8f6b42c….js:26flushPendingSave @ vendor-8f6b42c….js:26invokeWithOnError @ vendor-8f6b42c….js:5flush @ vendor-8f6b42c….js:5flush @ vendor-8f6b42c….js:5end @ vendor-8f6b42c….js:5run @ vendor-8f6b42c….js:5join @ vendor-8f6b42c….js:5u.join @ vendor-8f6b42c….js:11handleEvent @ vendor-8f6b42c….js:17e.default.u.Mixin.create.m.handleEvent @ vendor-8f6b42c….js:16_bubbleEvent @ vendor-8f6b42c….js:16(anonymous function) @ vendor-8f6b42c….js:16dispatch @ vendor-8f6b42c….js:4v.handle @ vendor-8f6b42c….js:4d @ raven.js:329nrWrapper @ (index):7


raven.js:51 AdapterError: The backend responded with an error
'f820-4cc0-90c5'

Before all this I've seen an intercom error, but portia was going on, not sure if it's related.

**Comment by j2l** [comment]
Here it is:
frame.268abd17.js:8 POST https://api-iam.intercom.io/vjs/users/ping 403 (Forbidden)n @ frame.268abd17.js:8(anonymous function) @ frame.268abd17.js:8r @ frame.268abd17.js:8o @ frame.268abd17.js:8o @ frame.268abd17.js:8(anonymous function) @ frame.268abd17.js:15(anonymous function) @ frame.268abd17.js:13value @ frame.268abd17.js:8value @ frame.268abd17.js:3(anonymous function) @ frame.268abd17.js:3
/#/projects/101430?url=https%3A%2F%2Fwww.amazon.com%2Fb%2Fref%3Ds9_acss_bw_…CFYQQBCX25X06%26pf_rd_t%3D101%26pf_rd_p%3D2598542082%26pf_rd_i%3D1045024:1 Uncaught (in promise) {"error_message":"incorrect user_hash"}
(index):7 GET https://portia-beta.scrapinghub.com/api/projects/101430/spiders/www.amazon.com/samples 500 (Internal Server Error)

**Comment by j2l** [comment]
Afterg multiple attempts to create a spider and sample:
Error: Internal Server Error
portia-web-588b0fc20f75c7a6a2f54f275f0aa2c9.js:5:22045
AdapterError: The backend responded with an error
[Errno 2] No file or directory: 'spiders/www.amazon.com_1/4685-4c1d-b85c.json'

looks like some folder has wrong owner to me.

**Comment by j2l** [comment]
When refreshing the main browser page (not the embedded browser), created sample is not present anymore.

**Comment by dirtychash** [comment]
@jemjov Chrome has build in Web Developer tools. If using firefox i would use firebug.

**Comment by dirtychash** [comment]
@j2l Maybe portia has been install with wrong permissions.
I had some thing similar and just launched slyd with sudo.
Not sure if that would fix or not though.

**Comment by dirtychash** [comment]
I am running a stand alone version though so probably completely different.

**Comment by j2l** [comment]
Yeah, I'm speaking about the scrapinghub hosted Portia, not standalone.

**Comment by sagelliv** [comment]
Can you try recreating the spider (create a new spider with the same extraction) to see if the issue is resolved?

**Comment by HatemHusam** [comment]
Hi, I'm facing the same issue here .. anyone find a solution for that, please?

**Comment by GregBreak** [comment]
+1
