### ISSUE TITLE
RegEx - Can you set a global regex for all spider 

### ISSUE THREAD

**Issue by Gighub** [scrapinghub/portia#583]
HI,
Is it possible to create a REGEX that is globally available to all my spiders (50+)? I see that a REGEX is available in the spider I am working in but not a new spider..

If so, will this allow me to update the REGEX in the master copy and then have this automatically update all spiders?

Currently I cannot see this option, this is leading me to believe I will have to copy paster in to every new spider and if I need to update the REGEX I will have to do this in every spider?

**Comment by drprabhakar** [comment]
Adding global REGEX in UI is not available now. But you will be able to add REGEX patterns in pipeline and  import that pipeline in spider to use REGEX.

**Comment by Gighub** [comment]
Thank you for taking the time to answer.
