### ISSUE TITLE
http://slybot.readthedocs.org not found

### ISSUE THREAD

**Issue by mindaugasrukas** [scrapinghub/portia#584]

**Comment by ruairif** [comment]
Here you can find docs on [Portia](http://portia.readthedocs.io/en/2.0-docs/) and [slybot](https://github.com/scrapinghub/portia/tree/master/slybot/docs)

**Comment by mindaugasrukas** [comment]
see https://github.com/scrapinghub/portia/blob/master/slybot/README.rst
