### ISSUE TITLE
Incomplete instructions?

### ISSUE THREAD

**Issue by DonRichards** [scrapinghub/portia#594]
Following the instructions and I'm getting a 502 Bad Gateway. 

My exact steps

``` shell
$ git clone https://github.com/scrapinghub/portia
$ cd portia
$ vagrant up
$ vagrant ssh 
$  slyd
```

Open web browser to http://localhost:9001/

Getting a 502 error. 

What am I missing?

**Comment by wildgarden** [comment]
Changing the path according to #442 fixed it for me.
