### ISSUE TITLE
How to use perform login of portia?

### ISSUE THREAD

**Issue by Peter311** [scrapinghub/portia#601]
When crawl one website, I need to login the website first.So I confige the perform login of portia.But it still don't work.Can you give a video address or tutorial,How to use perform login of portia?Thanks very much!

**Comment by ruairif** [comment]
If the login requires Javascript interaction login is not possible at the moment

**Comment by taylorsmurphy** [comment]
Is this still true? This issue pops up at the top of google seaches for "portia login" so it could be useful to flag it as fixed, not being developed (and so don't use portia if javascript might be involved), or whatever the case may be.
