### ISSUE TITLE
what's the structural thought of portia's server-side?

### ISSUE THREAD

**Issue by Bruce-Dong** [scrapinghub/portia#607]
Hi, can you just describe the structural thought of portia's backgroud  , e.g.  what's the relatiionship between slybot and slyd ?

**Comment by ruairif** [comment]
Slyd is a dumb webserver for handling requests, performing some validation and then persisting those changes. It has some other endpoints, one of which is used for extracting data. This is done by loading up the requested spider and requested page and then extracting data from that page using slybot.
Slybot is the part that also extracts data and follows links during a crawl.
