### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by richardpenman** [scrapinghub/portia#624]
I noticed scrapy now supports Python 3 - will Portia as well?

**Comment by ruairif** [comment]
I've added preliminary python 3 support for extraction. It would be great if you could test it out and see if you can break it.
You will need to install the versions of slybot, scrapely and page_finder listed below:
https://github.com/scrapinghub/portia/pull/626
https://github.com/scrapy/scrapely/pull/98
https://github.com/scrapinghub/page_finder/commit/d2cc6ec2ab55b15338d1e257b19ab3a8075bf447
