### ISSUE TITLE
Portia 2.0

### ISSUE THREAD

**Issue by kode-ninja** [scrapinghub/portia#648]
Hi,

Which branch should I checkout to try Portia 2.0?

Thanks

**Comment by sagelliv** [comment]
Hi @kode-ninja,

You can use the `nui-develop` branch.

**Comment by kode-ninja** [comment]
Thanks.

It seems slyd fails to start when running "vagrant up". Any advice?

```
==> default: Installing collected packages: slybot
==> default:   Running setup.py develop for slybot
==> default:
==> default:     warning: no files found matching 'slybot/splash-script-combined.js'
==> default:     Creating /usr/local/lib/python2.7/dist-packages/slybot.egg-link (link to .)
==> default:     Adding slybot 0.13.0b28 to easy-install.pth file
==> default:     Installing slybot script to /usr/local/bin
==> default:     Installing portiacrawl script to /usr/local/bin
==> default:
==> default:     Installed /vagrant/slybot
==> default: Successfully installed slybot
==> default: Cleaning up...
==> default: Executing command: configure_nginx
==> default: Executing command: configure_initctl
==> default: Starting slyd service
==> default: =====================
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

**Comment by kode-ninja** [comment]
Hi,

Would docker work?

**Comment by eng1neer** [comment]
Is `portia-orm-on-django` branch is obsolete now and `nui-develop` should be used instead?

**Comment by ruairif** [comment]
`nui-develop` is also obsolete. We are now using `develop`. This should be released to `master` once we have the last few bugs fixed and the docs up to date.
@eng1neer How are you running portia at the moment? Using docker or vagrant?

**Comment by eng1neer** [comment]
@ruairif I'm trying to run it via docker, but I can't figure out how to create a new project. In the old UI it was sufficient to navigate to a URL and the project would be created automatically. In the new UI there's only a blank screen with an empty list of projects. Is there an API call that can be used to create a project?

**Comment by ruairif** [comment]
@eng1neer Could you try out the changes in #670 and see if that works for you

**Comment by eng1neer** [comment]
@ruairif That worked perfectly, thank you!
