### ISSUE TITLE
502 Bad Gateway?

### ISSUE THREAD

**Issue by yanjieee** [scrapinghub/portia#678]
![image](https://cloud.githubusercontent.com/assets/7811777/21791975/928cdee4-d721-11e6-9601-c57e451a9130.png)

I have run it on windows 7. But when I try to access the URL, it can't work like this.
It seems to run successfully, but I can't access the URL. What happened?

**Comment by ruairif** [comment]
Would you mind telling us what steps you used to install and run portia so we can recreate the issue?

**Comment by rikmendes** [comment]
Got the same after success install using vagrant+virtualbox setup instructions. 

now it seems my Portia is running, I can vagrant ssh, but no way to display the actual server.
