### ISSUE TITLE
An error when adding and then removing an annotation

### ISSUE THREAD

**Issue by eng1neer** [scrapinghub/portia#684]
When adding an annotation and then removing it right away an alert flashes and the console displays the following error:

```Error: Attempted to handle event `deleteRecord` on <portia-ui@model:annotation::ember3132:2aad-44da-b749|0e37-4d53-9d83> while in state root.loaded.updated.inFlight```

(I'm using a `develop` branch)

**Comment by ruairif** [comment]
That happens because the annotation still hasn't been created so it can't be deleted. Ideally there would be a request queue for each object so it could merge updates and prioritize deletes without throwing an error
