### ISSUE TITLE
Ubuntu server 16.04 fails

### ISSUE THREAD

**Issue by ebuy-4-you** [scrapinghub/portia#687]
with the same message in docker and virtualenv missing beinieri repo.

works only in vagrant with problems 

`W: The repository 'http://ppa.launchpad.net/beineri/opt-qt551-trusty/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/beineri/opt-qt551-trusty/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Command failed (exitcode: 100), exiting...
The command '/bin/sh -c /app/provision.sh         install_deps         install_splash         install_python_deps         configure_nginx         cleanup' returned a non-zero code: 1
➜  portia git:(master) ✗`

**Comment by ruairif** [comment]
The correct install instructions can be found [here](http://portia.readthedocs.io/en/latest/installation.html). If you can't install it in your current version of Ubuntu you can downgrade to Ubuntu 14.04 or install Portia using Docker or Vagrant instead.

The simplest way to use Portia is to install [Docker](https://docs.docker.com/engine/installation/linux/ubuntu/) and then run:

    docker run -v ~/portia_projects:/app/data/projects:rw -p 9001:9001 scrapinghub/portia
