### ISSUE TITLE
Urgent quick change on UX

### ISSUE THREAD

**Issue by glemiere** [scrapinghub/portia#690]
Hi!
I really Love Portia, this software as a very good potentials! However, a little detail mess everything up.

When you add some URLs, each url generate one button. But creating 200k buttons in one time is just destroying the video memory and crash the browser, and as you guess, being able to crawl more than 10 pages is clearly vital. This modification would be pretty fast to make : just don't append any button.

If you could also add a very quick system to allow us to parameter urls. Like being able to say : id from 1 to 9999999 instead of giving a huge list of almost identical links. But fix that browser crashing problem first ;)

Thank you!

**Comment by ruairif** [comment]
If all of your ids a sequential then we already have you covered.
You can create what we call a `generated url`:
To start creating a generated url fist you need to press the down arrow beside the `START URLS` section.
![generation_url](https://cloud.githubusercontent.com/assets/6472969/22142992/4fc2f176-def0-11e6-8a79-ab328d05d9ac.png)
When the dropdown opens you click on `Add generation url`
This will bring you to the create generation url window.
![generation_view](https://cloud.githubusercontent.com/assets/6472969/22143051/8ae1a40a-def0-11e6-99d2-560da60c42d3.png)
This window allows you to build up a url from different pieces.
Here is an example of a generated url that will start with all listing pages on the site using a range.
![generation_options](https://cloud.githubusercontent.com/assets/6472969/22143084/ab37f45c-def0-11e6-97f4-0b70f646cfc5.png)

If a generated url doesn't work for you why not try a `feed url`.
You can start creating a `feed url` in the same way that you would make a `generated url`.
You press the down arrow beside the `START URLS` section and select `Add feed url`
This will open the create feed url window.
![screenshot from 2017-01-20 09 18 06](https://cloud.githubusercontent.com/assets/6472969/22143285/6f408954-def1-11e6-9c9b-df5ba71388f8.png)
All you need to do is to provide a link to a file containing urls structured like [this](https://gist.githubusercontent.com/ruairif/13b26e76dd226cfe0e8f7dc0091d4f20/raw/640ee54e19fb4301d449bcd1028ff52074e80fae/gistfile1.txt) and whenever your spider starts it will download the file and start with the urls that it contains. This means that you can update the start urls for your spider without modifying it.

Hopefully this helps. As a rule if you need more than 10 start urls you should use generated and feed urls instead.

**Comment by glemiere** [comment]
Interesting, my interface doesn't look like that. I probably didn't install it correctly.

<img width="1277" alt="screen shot 2017-01-20 at 19 47 41" src="https://cloud.githubusercontent.com/assets/7260880/22161193/9d4b5ec0-df49-11e6-887b-bcfecb6435e5.png">

**Comment by sagelliv** [comment]
@glemiere That is the previous Portia version. For a more up to date version, check out the [develop branch](https://github.com/scrapinghub/portia/tree/develop)

**Comment by glemiere** [comment]
Here was my mistake! Awesome thank you ;-)
