### ISSUE TITLE
slyd: unrecognized service

### ISSUE THREAD

**Issue by oshliaer** [scrapinghub/portia#698]
Hi! I'm new.

- This is a new installation
- I can't reach the `localhost:9001` from my host (it's all on a computer).
- I can't start slyd

#### `uname - a`
`Linux bigpc 4.8.0-37-generic #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
#### `vagrant --version`
`Vagrant 1.9.1`
#### Vagrantfile
```
# vim:ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.host_name = "portia"
  config.vm.provision :shell, :path => 'provision.sh', :args => ["install_deps", "install_splash", "install_python_deps", "configure_nginx", "configure_initctl"]
  config.vm.network "private_network", ip: "33.33.33.10"
  config.vm.network "forwarded_port", guest: 9001, host: 9001
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end   
end
```
#### `portia git:(master) cb-in ./VERSION`
`16.02.1`
#### `/etc/sudores`
```
...
# User privilege specification
root    ALL=(ALL:ALL) ALL
vagrant ALL=(ALL) NOPASSWD: ALL
...
```
#### `VBoxManage showvminfo portia_default_1486139928704_33506`
https://gist.github.com/anonymous/34a66717a9422d66274c6221492845a2
#### `vagrant@portia:~$ ps waux | grep 'slyd\|nginx'`
```
root      1074  0.0  0.0  31556   800 ?        Ss   18:26   0:00 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
nginx     1076  0.0  0.0  31940  1644 ?        S    18:26   0:00 nginx: worker process                   
vagrant   1454  0.0  0.0  10460   936 pts/0    S+   18:33   0:00 grep --color=auto slyd\|nginx
```

## Description

```
vagrant@portia:~# sudo service slyd restart
slyd: unrecognized service
```

**Comment by justnoise** [comment]
Running into a similar issue on OS X (10.11.6).  I CAN start the slyd server but I can't connect:
```
~/d/portia ❯❯❯ telnet 127.0.0.1 9001                                                                                                                          
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```
I've tried restarting nginx and the slyd server but I still can't connect to the server.

**Comment by justnoise** [comment]
As a follow up to my previous comment, I'm kind of amazed that any of this might work?  nginx.conf references files that need to be symlinked into `/etc/nginx`,  there are references to a dist folder but that seems to have been removed back in October.  Any ideas what's going on here?

**Comment by oshliaer** [comment]
@justnoise, what does `sudo service slyd restart` return?

**Comment by ruairif** [comment]
@oshliaer Can you try running it using the new instructions and scripts here: https://github.com/scrapinghub/portia/pull/700

**Comment by oshliaer** [comment]
@ruairif Not success. It looks like #699 #701

**Comment by ruairif** [comment]
The correct install instructions can be found [here](http://portia.readthedocs.io/en/latest/installation.html)

**Comment by oshliaer** [comment]
@ruairif Thank you! Your job is great!
