### ISSUE TITLE
Crawler regex to exclude links

### ISSUE THREAD

**Issue by CTPAYC23** [scrapinghub/portia#703]
Hi,

I'm crawling a site with URLs in the format:
http://website.com/product/brand/id123/

I'm trying to exclude links like:
http://website.com/product/brand/id123/doc/
http://website.com/product/brand/id123/txt/

so configuring crawling exclusions.
Tried:
doc
/doc/
\/doc\/
.*\/doc\/

but still seeing a lot of crawling attempts for http://website.com/product/brand/id123/doc/ pages in the request log of Scrapinghub. The ratio of scraped to requests is too low and the job gets eventually stopped.

What is the right way of excluding URLs like these please?

**Comment by ruairif** [comment]
Can you using a follow rule like: `\d+(/$|$)` instead?

**Comment by CTPAYC23** [comment]
@ruairif , ok trying that now.
Can I still combine _follow_ and _exclude_ rules successfully?

**Comment by ruairif** [comment]
You can. It follows all links that match the follow rules but not the exclude rules
