### ISSUE TITLE
Portia install on windows

### ISSUE THREAD

**Issue by devensonas** [scrapinghub/portia#711]
Hi, i tried Vagrant and docker to install Portia on windows but always get errors, maybe somebody have step by step guide to install correctly? Or ready to use VMware or Virtualbox image?

**Comment by ruairif** [comment]
Which instructions did you follow? The most up to date instructions and scripts can be found [here](https://github.com/scrapinghub/portia/pull/700)

**Comment by devensonas** [comment]
I tried this

1. mkdir portia
2. cd portia
3. git clone https://github.com/scrapinghub/portia.git
4. cd portia
5. git checkout update_installation
6. mkdir ~/data
7. cd portiaui
8. npm install && bower install
9. cd node_modules/ember-cli && npm install && cd ../../ && ember build
10. cd ..
11. docker build -t portia:v1 .
12. docker run -i -t --rm -p 9001:9001 -v ~/data:/app/data/projects ~/portia/portia/portiaui/dist:/app/portiaui/dist portia:v1
13. Point a browser to localhost:9001

**Comment by ruairif** [comment]
Did it work? Did you try to use the vagrant instructions?

**Comment by devensonas** [comment]
Yes i tried this. But i get an error.

**Comment by devensonas** [comment]
Maybe you can sent me step by step instruction with "vagrant" maybe i do something wrong?

**Comment by devensonas** [comment]
Sorry for writing again, but maybe somebody can help me install PORTIA on Windows or on Ubuntu? I am trying 3 days, nothing helped.  Please sent me step by step instructions ar contact me by skype:devensonas for helping me...

**Comment by ruairif** [comment]
Vagrant instructions are [here](https://github.com/scrapinghub/portia/blob/5d715734fbdc85a5806ba46221df16d3bc1bc8ce/docs/installation.rst#vagrant)

**Comment by devensonas** [comment]
Install using docker i get error:
`devensonas@ubuntu:~$ sudo docker run -i -t --rm -v projects:/app/data/projects:rw -p 9001:9001 scrapinghub/portia
/app/slyd/bot.py:40: ScrapyDeprecationWarning: scrapy.spider.BaseSpider is deprecated, instantiate scrapy.spider.Spider instead.
  spider = BaseSpider('slyd')
/app/slyd/tap.py:59: ScrapyDeprecationWarning: scrapy.settings.CrawlerSettings is deprecated, instantiate scrapy.settings.Settings instead.
  crawler_settings = CrawlerSettings(settings_module=slyd.settings)
/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py:170: ScrapyDeprecationWarning: `Settings.overrides` attribute is deprecated and won't be supported in Scrapy 0.26, use `Settings.set(name, value, priority='cmdline')` instead
  if opt_name in self.overrides:
/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py:174: ScrapyDeprecationWarning: `Settings.defaults` attribute is deprecated and won't be supported in Scrapy 0.26, use `Settings.set(name, value, priority='default')` instead
  if opt_name in self.defaults:
/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py:184: UserWarning: You do not have the service_identity module installed. Please install it from <https://pypi.python.org/pypi/service_identity>. Without the service_identity module and a recent enough pyOpenSSL tosupport it, Twisted can perform only rudimentary TLS client hostnameverification.  Many valid certificate/hostname mappings may be rejected.
  verifyHostname, VerificationError = _selectVerifyImplementation()
2017-02-23 06:23:09+0000 [-] Log opened.
2017-02-23 06:23:09+0000 [-] twistd 14.0.0 (/usr/bin/python 2.7.3) starting up.
2017-02-23 06:23:09+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2017-02-23 06:23:09+0000 [-] Site starting on 9001
2017-02-23 06:23:09+0000 [-] Starting factory <twisted.web.server.Site instance at 0x467f518>

`

in firefox:

`No Such Resource

No such child resource.`

What is wrong?

**Comment by ruairif** [comment]
You need to mount the dist directory too so that assets are available in the docker image

**Comment by devensonas** [comment]
How to do this?

**Comment by arcontechnologies** [comment]
Sorry but Vagrant isn't work either. I tried several time and still the issue there. 

==> default: Installing collected packages: slybot
==> default:   Running setup.py develop for slybot
==> default:
==> default:     warning: no files found matching 'slybot/splash-script-combined.js'
==> default:     Creating /usr/local/lib/python2.7/dist-packages/slybot.egg-link (link to .)
==> default:     Adding slybot 0.13.0b28 to easy-install.pth file
==> default:     Installing slybot script to /usr/local/bin
==> default:     Installing portiacrawl script to /usr/local/bin
==> default:
==> default:     Installed /vagrant/slybot
==> default: Successfully installed slybot
==> default: Cleaning up...
==> default: Executing command: configure_nginx
==> default: Executing command: configure_initctl
==> default: Starting slyd service
==> default: =====================
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by ruairif** [comment]
The correct install instructions can be found [here](http://portia.readthedocs.io/en/latest/installation.html)
