### ISSUE TITLE
Bug when clicking "copy" on a spider.

### ISSUE THREAD

**Issue by SeanBannister** [scrapinghub/portia#715]
I'm currently using Portia on ScrapingHub, when you click copy...

![image](https://cloud.githubusercontent.com/assets/197231/23210743/abd05570-f94a-11e6-93e0-78f0a599f2dd.png)

The copy button breaks and nothing happens...

![image](https://cloud.githubusercontent.com/assets/197231/23210750/b6746ef8-f94a-11e6-8bb8-054fa27a455b.png)

Using Chrome 56.0.2924.87 (64-bit)

**Comment by ruairif** [comment]
Hi Sean. Is this your only project in Scrapinghub or do you have another project that you are trying to copy it to?

**Comment by SeanBannister** [comment]
Hi, yes this is my only project, I presumed this would create a copy of the spider in the current project which I could work from. I'll try creating another project.

**Comment by SeanBannister** [comment]
Ahh yes, creating a second project works, I can copy to another project but I can't create a duplicate in the current project. I'm new to portia so maybe copying in the same project doesn't make any sense, the reason I was using this feature was to create a temporary backup.

**Comment by ruairif** [comment]
If you publish before making edits to a spider you can discard the changes to restore the spider to its previous state. If you want to test the modified spider you can press the run button and it will run the edited spider so you can see if it crawls as expected or not.
![run_spider](https://cloud.githubusercontent.com/assets/6472969/23211386/d0cc49b6-f8f9-11e6-934e-d1b78e69a908.png)

I'll discuss with the others and see if we should allow copying a spider to the same project.

**Comment by SeanBannister** [comment]
As a minimum maybe display a message when there's only 1 project: "Please create a project to copy this spider to"

Thanks for your help.
