### ISSUE TITLE
Could portia2.0 support pageaction?

### ISSUE THREAD

**Issue by ChoungJX** [scrapinghub/portia#716]
These days,I used the portia2.0.Compared to 1.0,I found that the portia2.0 have no `pageaction`.(I can't found).So,how to make portia2.0 support `pageaction` or `pageaction` had been replaced?
By the way,when I use portia1.0`(Had opened enable js ,set pageaction,set SPLASH_URL and opened splash when I crawled)`,some page just crawl some Javascript.Some action had no response,like click and scroll.
I wanna know why has that happened?

**Comment by ruairif** [comment]
Page actions were unreliable in Portia so we removed them for now. We are looking at reimplementing them but they are not the highest priority at the moment
