### ISSUE TITLE
Stuck at ==> default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US

### ISSUE THREAD

**Issue by codearm2** [scrapinghub/portia#724]
Hi,

I'm using Vagrant on Windows to install Portia

But it always stuck at **==> default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US**
I've left it for 3 hours and it's still not working

Any idea how to bypass the error?

**Comment by ruairif** [comment]
I've just run:
```
git clone git@github.com:scrapinghub/portia.git
cd portia
git checkout develop
cd portiaui
npm install && bower install && ember build
cd ..
mkdir -p data/projects
vagrant up
```
Everything works as expected when I visited `127.0.0.1:9001`
