### ISSUE TITLE
fail install 404

### ISSUE THREAD

**Issue by Royalxm** [scrapinghub/portia#726]
I have this error in debian or ubuntu same :( 

```
W: The repository 'http://ppa.launchpad.net/beineri/opt-qt551-trusty/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/beineri/opt-qt551-trusty/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by ruairif** [comment]
The correct install instructions can be found [here](http://portia.readthedocs.io/en/latest/installation.html). If you can't install it in your current version of Debian or Ubuntu you can downgrade to Ubuntu 14.04 or install Portia using Docker or vagrant instead.

The simplest way to use Portia is to install [Docker](https://docs.docker.com/engine/installation/linux/ubuntu/) and then run:

    docker run -v ~/portia_projects:/app/data/projects:rw -p 9001:9001 scrapinghub/portia
