### ISSUE TITLE
where has Portia source been downloaded in my ubuntu machine when I use Docker?

### ISSUE THREAD

**Issue by hesen1121** [scrapinghub/portia#751]
I use Docker to download the Portia image, then where has the Portia source been downloaded?I can't find it in my machine.

**Comment by hackrush01** [comment]
The source will downloaded inside the docker container most probably. Try this and tell if this seems to work for you
1. Run portia using `docker run -i -t --name portia --rm -v <PROJECTS_FOLDER>:/app/data/projects:rw -p 9001:9001 scrapinghub/portia`
1.  Open a new terminal and run `docker exec --it portia /bin/bash`
1. You should be inside the docker container in `/app/slyd` directory, if not then do `cd /app/`
This directory should contain the source code of portia.
