### ISSUE TITLE
portia 2.0

### ISSUE THREAD

**Issue by ShallMate** [scrapinghub/portia#757]
I should install portia2.0 sucessfully ,but I can not read the website,it can not enter。

**Comment by hackrush01** [comment]
@ShallMate Can you please describe what problem are you facing. Details would be helpful such as, which installation procedure did you follow, what steps did you take till now, are you receiving any error messages?

**Comment by ShallMate** [comment]
I run the portia and create the project .I need to input the URL. But the website does not show. I also install the 1.0。will they conflict?

**Comment by hackrush01** [comment]
Are you running it using docker or vagrant or directly installed on ubuntu?

**Comment by ShallMate** [comment]
I using the docker. I install it on ubuntu 16.04

**Comment by ruairif** [comment]
If you use `docker pull scrapinghub/portia:2.0.5` it should work

**Comment by ShallMate** [comment]
Thank you very much. I will try. I wish Portia become better and better.
