### ISSUE TITLE
Regular Expressions for Dynamic URLs

### ISSUE THREAD

**Issue by astarsign** [scrapinghub/portia#77]
Trying to understand applying regular expressions to follow patterns,

I have a site which has content I want to scrap from;
www.somesite.com/directory/page.php?var=1
to 
www.somesite.com/directory/page.php?var=6500

Any pointers on how and where I add regular expressions?

**Comment by SophiaCY** [comment]
So do you solve the problem? I also want to know that!
Thank you very much!

**Comment by ruairif** [comment]
There's currently no support for adding URL variables. We have been looking to add it but it's not a priority at the moment.
