### ISSUE TITLE
When i install the protia in linux system.there was a question when i want to start it

### ISSUE THREAD

**Issue by 158793034** [scrapinghub/portia#789]
when i excute the statement : <twistd -n slyd> to start portia .but there was a error !!!
twistd: Unknown command: slyd

How did i do  to start the portia? thanks a lot.

**Comment by katiaH** [comment]
Hi !

Are you running this command in portia/slyd directory?
When you execute the pip show twistd command, what is the result?

**Comment by 158793034** [comment]
thanks for you attention , i was run it successful ! thans a lot

**Comment by haris767** [comment]
when i excute the statement : <twistd -n slyd> to start portia .but there was a error !!!
twistd: Unknown command: slyd

How did i do to start the portia? thanks a lot.

**Comment by haris767** [comment]
when i excute the statement : <twistd -n slyd> to start portia in vscode  but there was a error !!!
twistd: Unknown command: slyd

**Comment by haris767** [comment]
help me out
