### ISSUE TITLE
Build Docker Images, Error: standard_init_linux.go:178: exec user process caused "no such file or directory" 

### ISSUE THREAD

**Issue by briankpw** [scrapinghub/portia#794]
I am Build Docker Images, When i am following all steps when i run the docker run, its come out the error: standard_init_linux.go:178: exec user process caused "no such file or directory" 

![image](https://cloud.githubusercontent.com/assets/15259963/25946961/e4952ba2-367f-11e7-98d9-ebee0c2b4a26.png)

The steps I am following. 
Step 1
mkdir portia
cd portia
git clone https://github.com/scrapinghub/portia.git
cd portia
git checkout update_installation
mkdir ~/data
cd portiaui
npm install && bower install
cd node_modules/ember-cli && npm install && cd ../../ && ember build
cd ..
docker build -t portia:v1 .
docker run -i -t --rm -p 9001:9001 -v ~/data:/app/data/projects ~/portia/portia/portiaui/dist:/app/portiaui/dist portia:v1
Point a browser to localhost:9001
From [https://github.com/scrapinghub/portia/issues/699](url) that i am following 

Step 2
mkdir ~/data
git clone git@github.com:scrapinghub/portia.git
cd portia/portiaui
npm install && bower install
cd node_modules/ember-cli && npm install && cd ../../
ember build
cd ..
docker build . -t portia

Thank You

**Comment by meteoric9637** [comment]
Hi briankpw, I faced same problem in my case. Did you solve the problem?

**Comment by briankpw** [comment]
Hi Meteoric,

Currently the problem haven't solve yet. But I found different of error. There is some requirement files with version error. 

Solution to fix it. 
**portia\slybot\requirements.txt**
#Slybot requirements
numpy==1.11.3
Scrapy==1.2.2
scrapely==0.13.2
loginform==1.2.0
lxml
dateparser==0.5.1
python-dateutil==2.4.2
jsonschema==2.4.0
six==1.10.0
scrapy-splash==0.7.1
page_finder
chardet==2.3.0

**portia\portia_server\requirements.txt**
crochet==1.6.0
django==1.10.5
django-cache-machine==0.9.1
djangorestframework==3.4.1
dj-database-url==0.4.2
drf-nested-routers==0.11.1
dulwich==0.16.2
marshmallow==2.8.0
marshmallow_jsonapi==0.10.0
wheel
MySQL-python
requests==2.12.4
toposort==1.5
whitenoise==3.2.3
portia2code==0.0.12

Install the software
**Visual C++ 2015 Build Tools**
http://landinghub.visualstudio.com/visual-cpp-build-tools

**Microsoft Visual C++ Compiler for Python 2.7**
https://www.microsoft.com/en-us/download/details.aspx?id=44266

After solved the problem, i faced still faced some error. You can try it

**Comment by liwei-box** [comment]
it's caused by git for windows, line breaks are forced to dos format
step 1: git config --global core.autocrlf false
step 2: delete code and git clone again

**Comment by haurbano** [comment]
@liwei8301 Hi, thanks for your answer, i have the same problem but I don't have a remote repository yet. Do you have another idea?

**Comment by liwei8301** [comment]
@haurbano sorry, now i don't another idea, may be you can save your dockerfile from windows to unix format by notepad plus, and try it again.

**Comment by briankpw** [comment]
I try to solve it with install  ember and bower with nodes. 
**Run this code with nodes.**
mkdir ~/data
git clone git@github.com:scrapinghub/portia.git
cd portia/portiaui
npm install && bower install
cd node_modules/ember-cli && npm install && cd ../../
ember build
cd ..
**After that use docker to build**
docker build . -t portia

its successful build
