### ISSUE TITLE
Vagrant/VirtualBox VERR_REM_VIRTUAL_CPU_ERROR 'GURU_MEDITATION'

### ISSUE THREAD

**Issue by jpswade** [scrapinghub/portia#81]
I installed Vagrant and VirtualBox, cloned the repo and ran vagrant up as per the instructions.

The install completed, but the VM would not run...

Here's a log: https://gist.github.com/jpswade/fb6131a3f0da41f79cdd

The VM has a 'GURU_MEDITATION' state, which seems to prevent me from doing anything with the VM. I can't even change the settings or remove it.

Thanks.

**Comment by Unfriended** [comment]
jpswade, when you mean "Rebooting the system", do you mean the Host or the Guest OS
