### ISSUE TITLE
MysqlStorage ?

### ISSUE THREAD

**Issue by cbaudras** [scrapinghub/portia#825]
Hi guys,

I'm trying to store projects/spiders in a Mysql DB. According to the [documentation](http://portia.readthedocs.io/en/latest/projects.html) I should be able to do something like that in _local_settings.py_ file in the _slyd/slyd_ directory:
```
SPEC_FACTORY = {
    'PROJECT_SPEC': 'slyd.gitstorage.projectspec.ProjectSpec',
    'PROJECT_MANAGER': 'slyd.gitstorage.projects.ProjectsManager',
    'PARAMS': {
        'storage_backend': 'slyd.gitstorage.repo.MysqlRepo',
        'location': os.environ.get('DB_URL'),
    },
    'CAPABILITIES': {
        'version_control': True,
        'create_projects': True,
        'delete_projects': True,
        'rename_projects': True
    }
}
```
1 - _slyd.gitstorage.repo.MysqlRepo_ does not exist but _db_repo.repo.MysqlRepo_ does.
2- SPEC_FACTORY is only called in _specmanager.py_ which doesn't seem to be used anywhere.

There is a `PORTIA_STORAGE_BACKEND = 'storage.backends.FsStorage'` option which seems to be the one to use, but I can't find any MysqlStorage although there is a SQL migration for Django in _portia_server/db_repo/migrations_ with the proper tables _objs_ and _refs_

So, I'm a bit confused here. Can anyone point me in the right direction ?

**Comment by ruairif** [comment]
Hi @cbaudras here's a PR that fixes the Git Filesystem backend. The MySQL backend is very similar and should just work. To enable it use `db_repo.repo.MysqlRepo` [here](https://github.com/scrapinghub/portia/pull/823/files#diff-72cc52997a514a179ac2c518f63d17f8R26)

**Comment by cbaudras** [comment]
Thanks @ruairif , it did the trick !
