### ISSUE TITLE
Infinite page loading

### ISSUE THREAD

**Issue by CroCoder** [scrapinghub/portia#838]
On some sites portia application gets halted (cannot add new start urls or sample pages) because the page is still loading (infinitely).

How to prevent this from happening?

**Comment by ayushmankoul** [comment]
Hey, @CroCoder If you can provide an example of the issue that will be a very great clue to understanding the problem and work on it.

**Comment by PaoloC68** [comment]
I try to set as start page this one [https://society6.com/tapestries](https://society6.com/tapestries) and I have the same behaviour

**Comment by PaoloC68** [comment]
@ayushmankoul It seems that you have a quite serious problem to fix 
<img width="960" alt="screen shot 2018-03-13 at 00 29 18" src="https://user-images.githubusercontent.com/1483774/37321112-a2b2d95c-2655-11e8-8a1b-932d8bf2280c.png">

**Comment by ayushmankoul** [comment]
Thank You @PaoloC68 for responding.The given website is based on react JS which is not supported by Portia as of now. [reference](http://portia.readthedocs.io/en/latest/faq.html).
I am interested in contributing to Portia as part of GSoC 2018 on this [ Increase Crawling Performance through page clustering](http://gsoc2018.scrapinghub.com/ideas/ ).Any guidance from you will be a great help to me.
