### ISSUE TITLE
Change the URL associated with a template

### ISSUE THREAD

**Issue by jpswade** [scrapinghub/portia#86]
Problem 1: If another URL isn't quite working with the template as expected, you may want to edit the template annotations on a different URL
Problem 2: If the original URL you used to create the template goes away you may wish to change the URL associated with the template

When you are browsing, perhaps there should be an option to assign the current URL to the template.

When you are in the template, you should be able to change the URL

**Comment by ruairif** [comment]
It is not currently possible but it would be nice to have.
A more in depth explanation can be found in #134
